### ISSUE TITLE
Create backend registration and authentication

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#1]
### Description

In order for users to save their configuration a login and registration system has to be setup.

![Image](https://user-images.githubusercontent.com/32770108/199461037-88c9a80d-4554-4764-95b6-94e89ca08b14.png)

The only thing in the design is a registration button but a start can be made on creating a simple registration page, allowing users to login and logout and creating a simple profile page.

### To discuss

- What information of the user should be stored? 

**Seth:** Name, Email, Challenge and storyline progress, and Sandbox scenario's (later on)

- Which tests should be added?
- Social media login?

**Seth**: Not required unless very easy

- Which level of security is required? 2FA, Confirmation email, ? -> 
**Seth:** confirmation email

### Acceptance criteria

- [ ] A user can login to the application
- [ ] A user can register in the application
- [ ] A user can update their personal information (name, email)
- [ ] A user can change their password
- [ ] A user can request a new password
- [ ] A user can remove their account
- [ ] Add register/login button to header including name and logout when user is logged in
- [ ] Add mailhog for local development of mail
- [x] An admin can create an account for a user

**Comment by mattijsstam** [comment]
Examples of django registration implementations:

https://dj-rest-auth.readthedocs.io/en/latest/index.html
https://github.com/gothinkster/django-realworld-example-app/tree/master/conduit/apps/authentication

**Comment by mattijsstam** [comment]
- [ ] Create frontend pages (8)
- [ ] Implement authentication functionality in Django (16)
- [ ] Connect backend to frontend (8)
- [ ] Enable email in dev and prod (4)
- [ ] Testing + review (4)

**Comment by pascalalferink** [comment]
I have found a bug:

1. Log in via form,
2. At profiel page, click "uitloggen"
The button changes, but I am still seeing the Profiel pagina


![Image](https://user-images.githubusercontent.com/13336728/216984532-a67fc7b0-f1b8-4261-963f-f3c9236cd312.png)

**Comment by pascalalferink** [comment]
Another bug: 
After login,  on /inloggen you can't edit the fields Voornaam, Achternaam en E-mail
