### ISSUE TITLE
Users can browse and filter through storylines

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#109]
**Description**

In order to find a storyline which best suits a users need the user can browse and filter storylines as shown in the [design](https://xd.adobe.com/view/fdfd0445-f79f-426d-a864-c0cb70e3329b-a8ae/screen/0894e596-80aa-4387-b535-ee64b3c4497f)

![Image](https://user-images.githubusercontent.com/32770108/193812790-4671f0a1-824e-4460-88ee-9e9127568d1b.png)

The storyline block can be a simple block in the CMS where the content manager specifies where it will be in the hierarchy and then it gets rendered in the frontend.

**To discuss**

- Which sorting options should be available? 
- How is the grouping specified and how does this relate to the sorting functionality?
- Are multiple selections in the filter allowed?
- Should a content manager specify the default filters and sorting in the CMS?
- How many storyline blocks should be possible?

**Acceptance criteria**

- [x] Content managers should be able to add a storyline overview block to a page in the CMS
- [x] Content mangers can add an introduction title and text to a storyline overview page
- [x] Users can browse trough storylines
- [x] Users can filter storylines on Type rol and Type informatie
- [ ] Storylines can be sorted on?
- [ ] Storylines are grouped based on the Type rol metadata field

**Comment by pascalalferink** [comment]
A start has been made in branch "storyline"

1. It is possible to create an overview of storylines (see design in this issue).  (ScenarioOverlistPage)This reads all pages of type "Scenario". 
2. On the page you can filter for "roles" and "type of information". 
3. Each card represents a page of type "Scenario" and contains a title, description  and scenario-blocks

1. It is possible in Wagtail to create a scenario-page. 
2. This scenario page can contain multiple scenario-blocks
3. Each scenario block contains:

- title
- description
- solarpanels (min, max, default value, locked)
- windmills (min, max, default value, locked)

**Comment by pascalalferink** [comment]
Cards have been made:
![image](https://user-images.githubusercontent.com/13336728/195843738-d4483c9a-d46b-4528-8539-3536058d8787.png)

**Comment by pascalalferink** [comment]
Strorylines have been developed, but not all requirements were met:

- Content mangers can add an introduction title and text to a storyline overview page
In another branch this block is being developed.

- Storylines can be sorted on?
The sorting /  grouping is still not clear, therefore this cannot be built

- Storylines are grouped based on the Type rol metadata field
The sorting /  grouping is still not clear, therefore this cannot be built

**Comment by pascalalferink** [comment]
to be determined:

- sorting / grouping
- the logic of the backgroundcolors of cards
- the logic of the icons besides the labels

**Comment by pascalalferink** [comment]
Color can now be managed in wagtail

![Image](https://user-images.githubusercontent.com/13336728/199465229-342e9b12-d19c-4da5-ba92-a7fbad45d20e.png)


![Image](https://user-images.githubusercontent.com/13336728/199465385-7d3ad8a1-37d0-44c3-b0e4-f01479e21a45.png)

**Comment by pascalalferink** [comment]
Merge request: https://github.com/ZEnMo/Holon-webapp/pull/126
