### ISSUE TITLE
Users can get more information on terms in the wiki

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#110]
**Description**

As shown in the design terms which need an additional explanation are highlighted in the text and users can click on the highlight to get more information on a specific term. 

![Image](https://user-images.githubusercontent.com/32770108/196616865-0cfe8bf4-a94a-4b72-8cbb-b4e3834c9d89.png)
![Image](https://user-images.githubusercontent.com/32770108/196616919-5a8b4978-7e5b-4392-a21b-861c36f8ae8a.png)

**To dicuss**

- Is a term just a simple text with an explanation or is a wikipedia page needed that user can go to?
  - A term is related to a wikipedia page
- Is the explanation shown inline or in a popup? popup
- How is the term highlighted, does the content manager do this or is it highlighted automatically? Content manager

**Acceptance criteria**

- [ ] User can click trough to a statictermpage
- [ ] Users can click on a term to see an introduction
- [x] Content managers can insert terms in the richttext element
- [x] Staticterm pages are listed as terms in the richttext editor
- [x] Staticterm pages have a mandatory introduction
- [ ] Terms are "automatically" highlighted in texts on interactive content with an underline

**Comment by mattijsstam** [comment]
@pascalalferink @broekhuisg I created the option to reference a staticTermPage in the richtext as a link. When you select a text in a richtexteditor and click the " icon you can select an existing staticTermPage which is then included as a link.

A staticTermPage is a StaticPage with a mandatory introduction, Kasper said that the terms will always link to a staticPage, if in the future we need to add more page types this is possible.

Todo:

The api renders a term link in the following form `<a data-page-link="/term2/" data-introduction-text="test descirption">term2</a>` we have some limited control over the attributes in [handlers.py](https://github.com/ZEnMo/Holon-webapp/blob/110-users-can-get-more-information-on-terms-in-the-wiki/src/main/handlers.py#L8) but not over the tag or text of the link so we should add some functionalty in react which parses these links into a nice modal with a link.

**Comment by mattijsstam** [comment]
Inherit from termpage to make it more flexible in the future and easier to get all pages that can be terms by type

**Comment by pascalalferink** [comment]
- Clickable terms are marked with a dotted line
- When clicked, a modal appears with the test from the data-introduction-text




![Image](https://user-images.githubusercontent.com/13336728/201687272-4b1431c9-1816-4df4-9501-f5facea05563.png)

**Comment by pascalalferink** [comment]
@antw  / @broekhuisg  could one of you review this feature?
https://github.com/ZEnMo/Holon-webapp/pull/170
