### ISSUE TITLE
The content in a storyline does not have styling

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#132]
@pascalalferink de content in een storyline heeft nog geen styling, ik heb geprobeerd de storyline van het design na te maken maar het resultaat is nog niet helemaal volgens verwachting.

![image](https://user-images.githubusercontent.com/32770108/199919665-f46be51a-41f5-4a6d-9cd9-8aedcc9d8b07.png)

Het zou mooi zijn als het er zoveel mogelijk uitziet als het [design](https://xd.adobe.com/view/fdfd0445-f79f-426d-a864-c0cb70e3329b-a8ae/screen/2b23d2b5-55ff-4888-a092-b86df8167083/specs/) dit is wel wat de mensen aankomende dinsdag verwachten.

_Originally posted by @mattijsstam in https://github.com/ZEnMo/Holon-webapp/issues/130#issuecomment-1303079562_

**Comment by pascalalferink** [comment]
Most of it was already styled, 
I improved the styling of lists:

![image](https://user-images.githubusercontent.com/13336728/200800592-7881bad5-1872-4ba8-ab4f-9b26ca53f474.png)
