### ISSUE TITLE
Create static page with animation demo

### ISSUE THREAD

**Issue by broekhuisg** [ZEnMo/Holon-webapp#134]
There is no case for animation in this version is this addition documented in another story or somewhere else?

_Originally posted by @mattijsstam in https://github.com/ZEnMo/Holon-webapp/pull/130#discussion_r1013139358_

**Comment by mattijsstam** [comment]
Include in new stories for new design

**Comment by mattijsstam** [comment]
Use old animation for the deadline of 22 nov

**Comment by mattijsstam** [comment]
Add static page with animation and sliders that work

**Comment by broekhuisg** [comment]
In branch 133 we still have the Interactive Component. Didnt check if it is available in other branches, but in 133 it is :)
