### ISSUE TITLE
Contactblock toevoegen

### ISSUE THREAD

**Issue by mattijsstam** [Zenmo/Holon-webapp#136]
**Description**

In the developed block the content block was excluded from scope but never ended in a story. According to the [design](https://xd.adobe.com/view/fdfd0445-f79f-426d-a864-c0cb70e3329b-a8ae/specs/)

![Image](https://user-images.githubusercontent.com/32770108/199979712-ce03b737-b322-48cd-868c-5381e5669f2d.png)

**To discuss**

- Which options should be configured
  - Input fields
    - email
    - naam
    - bericht (optioneel)
    - bedrijf (optioneel)
    - vinkje, meld me aan voor de nieuwsbrief (optioneel)
  - Form handling
  - Texts
  - Receiving email
- Should the user receive a confirmation email
  - yes, from info@holontool.nl
- Should the project team receive a confirmation email
  - contactform@holontool.nl  
- Where is the filled in form data stored and who has access?
  - database

**Acceptance criteria**

- [ ] Content managers can add a contact form to the home or static page including image, title and introdcution text
- [ ] Users can fill in a contact form and send their information to the backend
- [ ] Users receive a confirmation mail after filling in the contact form
- [ ] The project team receives a copy of the email
- [ ] Fields are validated in the front and backend
- [ ] Form provides simple spam security (honeypot)

**Comment by Erikvv** [comment]
Is dit nog steeds een wens?

**Comment by Erikvv** [comment]
We gaan dit doen middels een forum.
