### ISSUE TITLE
Styling issues: Cards aren't styled properly + titleblock adjustments + alt text images

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#146]
Design:

![Image](https://user-images.githubusercontent.com/13336728/200510280-24102856-3513-448b-ada2-7b69bf272e7f.png)

Current situation:

![Image](https://user-images.githubusercontent.com/13336728/200510116-c1832d22-d59f-4deb-b598-f469e0431da0.png)

**Comment by MariaBee3** [comment]
TitleBlock two adjustments: 
- Make heading size for TitleBlock required and set default to h2; 
- Set right color when selecting purple background

**Comment by MariaBee3** [comment]
Alt text: when alt text is entered with an image or video this is not rendered in the frontend.

**Comment by MariaBee3** [comment]
Replace css class top:0 with top-0
