### ISSUE TITLE
Add Buttons to components

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#147]
Based on the design, some blocks need a button. these blocks are: 

1. Cards (Naar use cases en verdiepende informatie)
2. Text and media (Meer over Holon)

![Image](https://user-images.githubusercontent.com/13336728/200509072-66bf5e8f-dba7-4d51-96c2-db1efa7bffb4.png)

![Image](https://user-images.githubusercontent.com/13336728/200509279-0aac848d-6693-45a0-9ffd-e31fafdf15c1.png)

**Comment by MariaBee3** [comment]
This issue is addressed in #129

**Comment by Erikvv** [comment]
Is nu in orde.
