### ISSUE TITLE
Sorting of the cards is not possible

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#159]

**Comment by thesethtruth** [comment]
![Image](https://user-images.githubusercontent.com/78690362/200893844-7d42c862-9875-4acb-80e3-46b00c2237eb.png)

**Comment by thesethtruth** [comment]
Voorstel voor MVP: gewoon eruit halen

**Comment by pascalalferink** [comment]
placeholder is verwijderd:
![image](https://user-images.githubusercontent.com/13336728/203330388-97f35ef2-15e7-4d3c-951f-19123bd6fda3.png)
