### ISSUE TITLE
Users can view the case detail pages that provides in-depth information on the case

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#163]
![Image](https://user-images.githubusercontent.com/78690362/200895277-38e466ba-5cd3-4da1-9484-1d86fe72847b.png)

**Comment by thesethtruth** [comment]
https://xd.adobe.com/view/93ccf9cf-16e5-440d-8e78-bc80b6265035-c69f/screen/d70dd3b0-186a-49a4-922d-6b43aa4304d8

**Comment by mattijsstam** [comment]
Implemented by #174
