### ISSUE TITLE
Users can view KPIs in the storyline modes that are a result from the model run

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#166]
![Image](https://user-images.githubusercontent.com/78690362/201113094-b987cd43-8e4c-4add-b91c-6ecdd61c6164.png)

**Comment by mattijsstam** [comment]
Leave out "energiestromen"
Lokale, Nationale = radiobutten
Input = 2 objects with 4 variables

**Comment by thesethtruth** [comment]
@mattijsstam add field to the single/multi select (one for `label` and one for `value`)
