### ISSUE TITLE
Content managers can add animations to storylines

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#173]
Implements a feature of the total infographic design https://github.com/ZEnMo/Holon-webapp/issues/182 

**Description**

In the new design the animation consists of tiles that can be turned on or of by interactive settings. In order to prepare for future changes we shoul make the tiles as flexible as possible and the animation should render based on the following input:

- Active tiles
- Interactive element settings
- Hidden settings

For example

```
{
  settings: [
    {
      id: 1,
      name: "Tegels"
      animation_tag: "tiles",
      value: ["bedrijventerrein", "windmolenpark"]
    },
    {
      id: 2,
      name: "solarpanels",
      animation_tag: "solarpanels-roof",
      label: "Aandeel zon op dak",
      value: 2
    },
    {
      id: 2,
      name: "transport electrification",
      animation_tag: "transport-electrification",
      label: "Aandeel electrificatie transport",
      value: 4
    }
  ]
}
```

Based on these settings the correct tiles can be shown an each tile can respond to the setting changes of the relevant animation_tag

![Image](https://user-images.githubusercontent.com/32770108/202131183-14d486f1-1aa8-4f6f-ad71-40c8468e431c.png)

[design](https://xd.adobe.com/view/ec31459a-326a-4600-8b99-57361c92bace-b962/?fullscreen)

**To discuss**

- Should the tiles setting be mandatory or have a default value if empty?
- Should images still be possible on storylines?
- Do tiles have a fixed position or are they always pushed together?

**Acceptance criteria**

- [ ] Content managers can add animation controls by adding interactive elements (solved by #123)
- [ ] When the tiles setting is present an interactive image is build up from tiles settings
- [ ] The interactive animation responds to static and dynamic settings based on the animation_tag value

**Comment by Erikvv** [comment]
Tegels gaan we niet meer doen.
