### ISSUE TITLE
Content managers can add overview pages to quickly show a list of cards

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#174]
**Description**

In the mvp design a page is shown that lists its subpages in cards. We have the card block but it will be less fool proof if these pages are rendered automatically based on a type or child pages.

![Image](https://user-images.githubusercontent.com/32770108/202137520-80f79e02-619c-42a9-a03c-5823fc1abd0d.png)

[design](https://xd.adobe.com/view/93ccf9cf-16e5-440d-8e78-bc80b6265035-c69f/screen/6e38ad5d-6ffd-4eb5-8b02-4262cc3d90c0)

**To discuss**

- Are cases always under a single overview page or can they be in multiple?
Cases have a single theme category
- How should the overview page fill the cards, based on children or type?
Based on the cases created as children of the overview page.
- Should the storyline overview page still exist?
Yes. One overview page for **all** interaction mode with filter on pagetype.

**Acceptance criteria**

- [ ] Content managers can add overview pages in the CMS
- [ ] Content managers can specify the type of pages that are shown 
- [ ] Content managers can specify the default filters in an overview page, these are not shown to the user
- [ ] If there are more types or pages then filters are shown to the users
- [ ] Users can browse categories on overview pages
- [ ] Casus pages are automatically linked to their interaction modus
- [ ] Casus page contains the model data and interactive elements
- [ ] best practice pages can be linked to the casus page (best practices can relate to multiple casus and vice versa)
- [ ] Buttons from cases to interaction modes should automatically be generated

**Comment by mattijsstam** [comment]
@thesethtruth will add the schematic overview of the pages to this story so we can configure this in the CMS

**Comment by thesethtruth** [comment]
![cms architectuur](https://user-images.githubusercontent.com/78690362/202469140-00304490-8b53-458d-bc2b-336d8edb6908.png)

**Comment by broekhuisg** [comment]
![Image](https://user-images.githubusercontent.com/58260886/213664822-457dd72f-30f7-45ab-acd0-508e0d37479a.png)

**Comment by broekhuisg** [comment]
https://holontool.nl/casussen/provinciaal/bedrijventerrein-energy-hub/

**Comment by pascalalferink** [comment]
Cases overview has been made:


![Image](https://user-images.githubusercontent.com/13336728/214276276-09c50e74-7e02-4b47-b6c6-216d8fa519ca.png)


Buttons have been added:


![Image](https://user-images.githubusercontent.com/13336728/214276158-af787ede-1505-4a8c-8ddd-7e74fd8e8991.png)

**Comment by pascalalferink** [comment]
@mattijsstam  I have pushed some code for the many-to-may relation on a featurebranch named **many_to_many_poc**

**Comment by broekhuisg** [comment]
### Aanpassingen aan de content na migratie

Wanneer deze story is gemigreerd, zal het volgende met de content moeten gebeuren:
- Casussen moeten worden aangemaakt
- Best practices moeten worden aangemaakt
- Storylines koppelen aan casussen door deze onder de casus te hangen in de hierarchie
- Best practices <> Casus koppelen
- Uiteindelijk wanneer alle storylines verplaatst zijn naar casussen, mag de storylineoverviewpagina's worden verwijderd uit het CMS (content).
- Wanneer al deze content is verwijderd, zal het hele type ook uit de code gehaald worden, want deze wordt dan niet meer gebruikt.
