### ISSUE TITLE
Text block without title

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#179]
From content creator @naudloomans 

**Acceptance criteria**

- [ ] Content managers can add paragraph blocks with optional title
- [ ] Paragraph blocks can be added to static pages
- [ ] Width of the text has 1/3, 2/3 or full options
- [ ] Background colors can be chosen (color and only left/right/full)

Optional:
- [ ] Inherits from text and media `block` or other way around
- [ ] Compose this block from various others if possible

**Comment by mattijsstam** [comment]
Add new block "Paragraph block"

**Comment by pascalalferink** [comment]
Block has been made, see screenshots below. 
The block is a stripped version of the textAndMedia, The following options have been removed: columOrder, Media, altText and ButtonBock.


![Image](https://user-images.githubusercontent.com/13336728/211311014-b1975d90-0c4b-4266-b79b-18b818725951.png)


![Image](https://user-images.githubusercontent.com/13336728/211310922-90b1f769-f15f-484e-a44a-5fbdcba6557c.png)
