### ISSUE TITLE
Content managers can add table blocks in text fields

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#180]
From content manager @naudloomans 

Implement https://docs.wagtail.org/en/stable/reference/contrib/table_block.html in blocks for static pages

**Acceptance criteria**

- [x] Content managers can add table blocks to static content like paragraph blocks and wiki
- [x] Tables are rendered without large margins in the frontend
- [x] Check the look and feel with Kasper UI

**Comment by pascalalferink** [comment]
@thesethtruth In the cms of the wiki pages you only have field: Rich Text. With te proposed solution you can add a block with a table. This table can only be placed above/below the rich text. So it isn't possible to have a table between two paragraphs. Is this a problem?

**Comment by pascalalferink** [comment]
I forgot @thesethtruth  is out-of-office, so I have added a tableblock below the content of the wiki.  If a table block is required between paragraphs a new Story should be added.

Below is a screenshot of a table

1. A table has an optional table caption above the table
2. A table can have table headers (first column and/or first row), these are bold
3. Below each table row is a gray line.
4. In the cms it is possible to add/remove columns / rows to the table




![Image](https://user-images.githubusercontent.com/13336728/212862758-1d4b379c-92a8-431d-8f0e-d74f9d44eff9.png)

**Comment by pascalalferink** [comment]
I have spent more time than estimated, this was mainly caused by the following

1. I had troubles with empty cells: I expected them to be an empty quote, the were saved as `null `and in the frontend this was an objecte `{}`
2. There are two pages where tables can be added: but the structure of the data was different for these two pages.

I have asked Kasper for a review: if he approves, I will drag the task to Review

**Comment by pascalalferink** [comment]
The table has a max-width, which is the same as text-blocks and cards. When there isn't a lot of data in the table, the table isn't 100% width.



![Image](https://user-images.githubusercontent.com/13336728/213112254-3e01063d-847b-48f8-8fb3-bf74b641c4be.png)



![Image](https://user-images.githubusercontent.com/13336728/213112308-f07acf74-caed-4f6d-8fb5-66ff1d9bccb7.png)
