### ISSUE TITLE
The current slider doesn't show the values, this is confusing

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#186]
In the cms a moderator can add a slider with a minimum value, maximum value and default value.
These boundaries are not shown in the layout, so the user doesn't know what value he/she is sliding

![Image](https://user-images.githubusercontent.com/13336728/202727265-e24686d3-678e-43c1-b8d4-381b8330f058.png)

**Comment by Erikvv** [comment]
Opgelost.
