### ISSUE TITLE
InteractiveInput: when adding the same input twice, this causes issues

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#189]
when adding the same input twice, this causes issues because the name of the input also stays the same,  When there are two radio-groups with the same name, you can't select an item of both groupes

**Comment by mattijsstam** [comment]
![Image](https://user-images.githubusercontent.com/32770108/212286747-f91dc18f-4af4-4bbe-bd85-2a275070be7d.png)

**Comment by mattijsstam** [comment]
Concerns the inputs in the left column

**Comment by MariaBee3** [comment]
![Image](https://user-images.githubusercontent.com/70764188/214262763-3934f264-093a-4c66-8688-8ee78efd5cd7.png)
this was already fixed two months ago. The name of the input includes the content Id.
