### ISSUE TITLE
What is the reason to choose the django model setup instead of the streamfield setup which provides additional flexibility in the CMS with https://docs.wagtail.org/en/latest/advanced_topics/customisation/streamfield_blocks.html#additional-javascript-on-structblock-forms?

### ISSUE THREAD

**Issue by broekhuisg** [ZEnMo/Holon-webapp#190]
What is the reason to choose the django model setup instead of the streamfield setup which provides additional flexibility in the CMS with https://docs.wagtail.org/en/latest/advanced_topics/customisation/streamfield_blocks.html#additional-javascript-on-structblock-forms?

_Originally posted by @mattijsstam in https://github.com/ZEnMo/Holon-webapp/pull/188#discussion_r1026615602_

**Comment by Erikvv** [comment]
We gebruiken nu streamfields.
