### ISSUE TITLE
Hide the "Display" select box when the content manager selects the slider

### ISSUE THREAD

**Issue by broekhuisg** [ZEnMo/Holon-webapp#191]
When a content manager selects a slider as interactive input, the 'display' selectbox should be hidden in Wagtail, to avoid confusion.
Therefore you have to inject a custom js file

**Comment by thesethtruth** [comment]
I don't get this issue. It is a feature to be able to specify inputs that are not exposed to the user. In that way, scenario defaults can be overwritten in a storyline section, which is desirable.

**Comment by Erikvv** [comment]
Dit lijkt me niet zo belangrijk als het op usability aan komt. Sowieso gebruiken we nu wel onzichtbare sliders v.z.i.w. dus het zou lastig zijn als die optie weg valt.
