### ISSUE TITLE
Update the icons in the KPI dashboard and conditional division for financial numbers 

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#208]
A *maybe hacky* implementation using heroicons can be found at https://github.com/ZEnMo/Holon-webapp/commit/95fc8dd239d40c36e2f52706412d8d72fd4ea44e

Maybe we want to update the icons to icons made by Fleur.

**Comment by mattijsstam** [comment]
@MariaBee3 will take a look at #203 to check the kpi component

**Comment by MariaBee3** [comment]
@thesethtruth looks like a good implementation. I've cleaned it up a bit and made a few adjustments to the style, but otherwise it looks good.
