### ISSUE TITLE
Multiselect should be rendered as checkbox when provided with that function from the CMS

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#211]
Currently it doesn't?

**Comment by pascalalferink** [comment]
Tested it locally on the main branch: it worked:

I have added three screenshots:



![Image](https://user-images.githubusercontent.com/13336728/205038671-5d331697-fde7-4757-b960-860d119f155b.png)


![Image](https://user-images.githubusercontent.com/13336728/205038784-7e3ab919-4988-4c64-a843-8ec1f8e64653.png)




![Image](https://user-images.githubusercontent.com/13336728/205038813-2d062b84-9918-43c7-a863-69a057c38976.png)

**Comment by pascalalferink** [comment]
@thesethtruth  can you test if it also works for you?
