### ISSUE TITLE
Update on the styling of the current product based on the latest holon identity 

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#214]
See comments below!

**Comment by mattijsstam** [comment]
@pascalalferink will create an estimation with Kasper

**Comment by pascalalferink** [comment]
Algemeen:
Nieuwe achtergrondkleuren zijn nog niet voldoende uitgewerkt -> nog niet doen dus. We laten de kleuren zoals ze zijn.
- [ ] witruimte onder elk blok verkleinen

Header:
- [ ] kantlijn overnemen van content (het logo staat te ver naar links, laatste knop te ver naar rechts)

Buttons (er zijn alleen witte en blauwe buttons)

- [ ] optie "pijltje" toevoegen bij blauwe variant (pijltje altijd aan rechterkant)
- [ ] buttons geen border radius

Heroblock:

- [ ]  eerste lijn van tekst uitlijnen met bovenkant afbeelding
- [ ]  Line height van titel vergroten
- [ ]  lettergrootte en line-height ten tekst onder titel vergroten

Cards:

- [ ] geen ruimte tussen rand en foto
- [ ] border verwijderen
- [ ] labels in de foto ipv onderin kaart
- [ ] eerste kaart zelfde formaat als de overige kaartjes
- [ ] Groep met kaarten gecentreerd weergeven (ipv links uitlijnen) (altijd max 5 op 1 regel)
- [ ] Button mogelijkheid om rechts uit te lijnen


Text en Media:

- [ ] Mogelijkheid om positie te wisselen (afbeelding links, tekst rechts)

Wiki popup
- [ ] Knop is te breed, moet pijltje bevatten, en gecentreerd

**Comment by thesethtruth** [comment]
Thanks @pascalalferink. Ik mis in jouw overzicht:

- [ ] Styling van filterelement op storyline overview pagina
- [ ] Lichte knop optie (zoals in de mockup > onderin de casus)

Wat was de conclusie over de pagina breedte? (dus kleinere maximale breedte van de content, voor leesbaarheid)

**Comment by pascalalferink** [comment]
@thesethtruth 

1. Styling van filterelementen (checkboxes en radiobuttons) wordt gelijkgetrokken met de radio's en checkboxes die in de storyline staan
2. De lichte knop waaraan je refereert begrijp ik niet helemaal, maar dat komt wel goed
3. De paginabreedte moet gemaximaliseerd worden. Het aantal pixels hou je tegoed
Samen met @MariaBee3  heb ik de bovenstaande lijst doorgenomen: we kwamen uit  op  een totaal van 8 uur

**Comment by thesethtruth** [comment]
@pascalalferink Thanks, ga ik nu doorzetten

**Comment by pascalalferink** [comment]
Samen met Kasper heb ik de aanpassingen doorgenomen, deze zijn akkoord
