### ISSUE TITLE
After creating a Multi-select-snippet it is not possible to change the options

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#216]

**Comment by pascalalferink** [comment]
I created a multi-select-input with two options. After creation I want to change the options. This is not possible; the options are gone:


![Image](https://user-images.githubusercontent.com/13336728/205040499-5771c836-af0e-47c4-b7d8-01d00de047f0.png)

**Comment by pascalalferink** [comment]
Update: it is possible when you switch the type field back and forth to Multi Select

**Comment by mattijsstam** [comment]
Fixed in #203
