### ISSUE TITLE
Duplication of the API URL leads to mistakes in correct configuration of API calls 

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#223]
https://github.com/ZEnMo/Holon-webapp/blob/d523d04a8a49ac0afefd894de7b7d491b9f2620f/frontend/api/wagtail.ts#L7-L8
https://github.com/ZEnMo/Holon-webapp/blob/d523d04a8a49ac0afefd894de7b7d491b9f2620f/frontend/.env.example#L1-L2

The `NEXT_PUBLIC_WAGTAIL_API_URL` variable was not configured in Azure. Password protected pages and the 404 page depends on this variable from what I can see.

**Comment by thesethtruth** [comment]
Same problem occurred with the API_KEY env var

**Comment by mattijsstam** [comment]
Possible solitions

- bash comands to create javascript file at runtime: https://www.freecodecamp.org/news/how-to-implement-runtime-environment-variables-with-create-react-app-docker-and-nginx-7f9d42a91d70/ (bit hacky)
- nextjs runtime configuration: https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration (removes support for static site generation and optimization)
- Hardcoded url (allways /wt/api so no environment variable needed)
