### ISSUE TITLE
Button element should have a word-based line break (now it breaks halfway a word)

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#235]
![image](https://user-images.githubusercontent.com/78690362/206705626-926b94e4-ee5a-4866-bb96-b714e02e71e5.png)

**Comment by pascalalferink** [comment]
It works

![Image](https://user-images.githubusercontent.com/13336728/211590256-b13074c9-0eb3-406b-a012-aac7e9c6df60.png)
