### ISSUE TITLE
Include privacy statement in or around the subscription form

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#25]
Acceptance criteria:

- The sentiment/subscription form should have a link to the privacy statement
- The user should be notified that by clicking submit the privacy statement is accepted
- The privacy statement should be available at holontool.nl/privacy

**Comment by thesethtruth** [comment]
# Privacyverklaring Holontool inbreng

# Identiteit

Zenmo B.V. is als penvoerder van het Holon Consortium de verantwoordelijke rechtspersoon voor het zorgvuldig omgaan met je privacy.

 Adres:
 Zenmo B.V.
 Hoefstraat 1a
 5255PB Herpt

Kamer van Koophandel:
 Zenmo B.V.
 nummer: 71609113

 Contact inzake privacy: [david@zenmo.com](mailto:david@zenmo.com)

In deze verklaring vertellen we je hoe we met je gegevens omgaan.

# Oorsprong van gegevens

Alle gegevens komen uit het persoonlijke netwerk van het Holon consortium, een groep van experts en modelleurs die onderzoek doen naar semiautonome energiesystemen. Voor meer informatie over Holon, zie: [https://www.topsectorenergie.nl/nieuws/groot-onderzoekstraject-holon-van-start](https://www.topsectorenergie.nl/nieuws/groot-onderzoekstraject-holon-van-start)

# Doel

Het doel van de verwerking van de gegevens is slechts het vragen om input voor de holontool aan professionals werkzaam in de energiesector, bijvoorbeeld als beleidsmedewerker. De maillijst die hiervoor wordt gebruikt waar de gegevens in zitten, wordt slechts gedeeld met relevante leden van het Holon Consortium en dus absoluut niet daarbuiten.

# Duur van de opslag

De einddatum van het Holon project is op 15 juni 2023, dit is de maximale tijd dat je gegevens zullen zijn opgeslagen.

# Recht op inzag, rectificatie of wissen

Voor die tijd heb je ook al recht op het wissen van je gegevens uit deze maillijst. Ook heb je recht op inzage of rectificatie. Voor al deze zaken kun je contact opnemen met [david@zenmo.com](mailto:david@zenmo.com)

# Rechtsgronden

Voor de verwerking van deze gegevens zien wij in dit geval een zogeheten &quot;gerechtvaardig belang&quot; als grondslag. Dat betekent dat er een afweging is gemaakt tussen privacy van de personen in deze maillijst en Zenmo B.V. en daarmee Holon, waarbij de verwerking noodzakelijk is voor de verwerkingsverantwoordelijke Zenmo B.V.

 In makkelijke woorden: Zenmo B.V. kan haar werkzaamheden niet goed uitvoeren zonder via deze maillijst enquetes uit te sturen. Holontool beoogt beleidsmedewerkers te ondersteunen. Zonder de mening van beleidsmedewerkers te kunnen vragen, kan dit niet goed gebeuren.

# Klachtrecht

Wanneer je gegevens ergens verwerkt worden, dus ook voor deze maillijst, heb je het recht om een klacht in te dienen bij de Autoriteit Persoongegevens. Dit kan via: [https://www.autoriteitpersoonsgegevens.nl/nl/zelf-doen/gebruik-uw-privacyrechten/klacht-melden-bij-de-ap](https://www.autoriteitpersoonsgegevens.nl/nl/zelf-doen/gebruik-uw-privacyrechten/klacht-melden-bij-de-ap)

**Comment by mattijsstam** [comment]
@thesethtruth change email address

**Comment by thesethtruth** [comment]
> @thesethtruth change email address

Done, thanks!
