### ISSUE TITLE
Setting new assets / settings should be able to balance a group

### ISSUE THREAD

**Issue by thesethtruth** [Zenmo/Holon-webapp#255]
In scenariobuilder.

For instance, if a user increases the amount of electric trucs, the amount of diesel trucks should reduce. 

Should be configurable per interactive element mapping, to describe a group.

Acceptance:
 - CMSer should be able to define the data for the 'to be balanced' assets

**Comment by thesethtruth** [comment]
https://github.com/ZEnMo/HOLON-ETM/blob/main/src/etm_service/balancer.py

**Comment by TAVMWB** [comment]
![Image](https://user-images.githubusercontent.com/105435881/221823795-962c9b0f-ef68-42fc-8c0b-e0c827ab1e06.png)

**Comment by thesethtruth** [comment]
```
Voor te balanceren elementen [x_0 ... x_n] in volgorde:
Voor k != 0 en k != n:

- toename van x_k zorgt voor afname van x_n tot 0, daarna x_(n-1), ... tot x_k+1 
- afname van x_k zorgt voor toename van x_(k-1)

- Anders:
- toename van x_0 zorgt voor afname van x_n tot 0, daarna x_(n-1), ... tot x_k+1
- afname van x_0 zorgt voor toename van x_(0+1)
- toename van x_n zorgt voor afname van x_(n-1) tot 0, daarna x_(n-2), ... tot x_0
- afname van x_n zorgt voor toename van x_(n-1)
```

**Comment by TAVMWB** [comment]
TODO 
balancegroup balances nu assets binnen één gridconnection, terwijl het individuele assets voor een groep van gridconnections moet balancen. Verder moet het ook niet alleen kunnen voor de asset-gridconnection combinatie, maar bijv. ook voor contracts en actors. 
Correcte functionaliteit kan worden afgekeken van RuleActionAdd/SetCount
