### ISSUE TITLE
Remove old sliders

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#281]
![Image](https://user-images.githubusercontent.com/78690362/210752101-e699e975-de8c-490a-a778-3815fd01bae3.png)

Remove this option

**Comment by thesethtruth** [comment]
Doesn't relate to any content

**Comment by pascalalferink** [comment]
Option for slider is deleted
![Image](https://user-images.githubusercontent.com/13336728/211280887-8ef11669-9745-4acf-9e63-475176981ac1.png)
