### ISSUE TITLE
Storyline filters: checkboxes are not showing correct

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#291]
The checkboxes are getting squished when there is a long text in the adjecent label
![image](https://user-images.githubusercontent.com/13336728/211756803-045b1bc4-7c85-4b13-84c6-2df08443bdd7.png)

**Comment by Erikvv** [comment]
Als ik het goed begrijp is dit issue niet meer relevant. Want we doen geen filters meer op casussen.
