### ISSUE TITLE
Content managers can specify a wiki information window and legal limitation category for 'beleidsinstrumenten'

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#295]
**Design will be updated!**

![Image](https://user-images.githubusercontent.com/32770108/214293002-05e53a7e-42d8-4933-829c-9357be3b9c1c.png)

![Image](https://user-images.githubusercontent.com/32770108/214293037-9d1529bb-4732-40fc-b9ec-c33b7689638a.png)

Acceptance: 
1. Legal limitation status categories can be edited themselves (name, label and order)
2. Legal limitation status is rendered on the front end as described in the design (Kasper is working on the design); either a color code or text and seperation line.
3. The information icon is linked to the wiki pages in the same way that the the current implementation of 'terms' is implemented

**Comment by mattijsstam** [comment]
- [ ] Add (i) to radio with the same functionality as the wiki link
- [ ] Add juridische status to radio element

**Comment by mattijsstam** [comment]
vrije tekstinvoer voor toepasbaarheid
kleur kiezen rood, geel, groen
link naar wikipagina

extra velden per optie
alleen tonen wanneer tonen als radio & checkbox
