### ISSUE TITLE
When heroblock is not the first element, the scrolldown-button does not scroll downwards

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#296]
The button moves the viewport to the first thing below the fold, when this block is positioned somewhere below the fold, this button scrolls upward

![Image](https://user-images.githubusercontent.com/13336728/206451467-fbf27838-b759-4b67-b7f5-31f7a79f7a80.png)

**Comment by mattijsstam** [comment]
- [ ] Make the arrow scroll to the next block
- [ ] Make the arrow optional in the hero block 

Discuss with Kasper if this is neccesary and what should be the desired functionality

**Comment by pascalalferink** [comment]
I had a discussion with Kasper about this arrow: the conclusion is that we can remove the arrow and it's functionality
