### ISSUE TITLE
Storyline: slider has no default value, so the tooltip is broken

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#297]
The value is NaN. This causes the toolitp to position somewhere offscreen to the right. Which causus a horizontal scrollbar.

![image](https://user-images.githubusercontent.com/13336728/211833659-c4a05441-e2bb-4f3c-b049-bda95eed7fcf.png)

**Comment by Erikvv** [comment]
Is al opgelost
