### ISSUE TITLE
Users can view information related to an interactive input

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#303]
![Pop_over_sliders](https://user-images.githubusercontent.com/78690362/214611805-11df2567-3f03-4204-8d3b-ca1cf8d41069.jpg)

To discuss:
- Should we use a wiki page or should we make a popover like in #295 

Acceptance criteria:
- Information icon is rendered next to the title text of the slider
- Information popover is rendered similar to #295 but without the 'juridische toepasbaarheid'
- Content of the information popover is specified at the interactive element snippet level
- If no information is specified, no icon is rendered
- Content managers can specify a static text that is rendered in the popover
- Content managers can specify a wiki link that is rendered as a read more button

**Comment by mattijsstam** [comment]
frontend component generiek
backend specifiek in te richten
