### ISSUE TITLE
Content managers can configure modals that appear based on conditions in the challenge mode

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#304]
![pop_up_if_confetti](https://user-images.githubusercontent.com/78690362/214611653-0f5cf571-69b4-4a71-b142-628adb8040a6.jpg)
![pop_up_if](https://user-images.githubusercontent.com/78690362/214611663-a5dca070-fa63-490c-8404-3eedeae04f7b.jpg)

To discuss:
- How do we deal with conditions for single select (value field / label field dropdown?)

Acceptance criteria:
- Conditions that can be used are `==` `<` `>` `=<` `=>` `!=`
- Conditions can be based on `interactive elements` (sliders and single select) and `dashboard results`
    - nationaal & lokaal
    - condition is placed with the slider
- Multiple conditions can be combined for a single modal and are always and condition
- The modal can be styled:
    - Color (red, green and orange)
    - Optional image (gif)
    - Additional buttons in buttongroup (default button = 'ga door'), additional buttons with page links are possible
- The modal resizes vertically based on the content to minimal size if no image / subtext is present
- Modal is shown after the calculation of kpi's is finished
- Only the last modal is shown
- Ga door of naast klikken sluit de modal

**Comment by pascalalferink** [comment]
A start has been made:

- One modal that consistst of three themes (green, orange, red)
- 

![Image](https://user-images.githubusercontent.com/13336728/215480766-5f6c9cb9-d382-44f0-9ab3-623b3650426c.png)

**Comment by pascalalferink** [comment]
**modal themes:**
- green, 
- orange, 
- red

**parameters:**
- localcosts
- localnetload
- localself_sufficiency
- localsustainability
- nationalcosts
- nationalnetload
- nationalself_sufficiency
- nationalsustainability
- interactive_input (one of the sliders / inputs)

**operators:**
- parameter is lower then value: lower
- parameter is lower or equal then value: lowerequal
- parameter is bigger or equal then value: biggerequal
- parameter is bigger then value: bigger
- parameter is equal to value: equal
- parameter is not equal to value: notequal

**Comment by pascalalferink** [comment]
Frontend has been made:
