### ISSUE TITLE
Gebruikers kunnen navigeren naar de sandbox pagina

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#305]
- [ ] Via casus pagina bereikbaar (zelfde als challenge en verhaallijn)
- [ ] 1 sectie
- [ ] Alleen beleidsmaatregelen (verantwoordelijheid van CMSer)
- [ ] Dashboard wordt grijs als tegelinstellingen aangepast (resultaten blijven staan)
- [ ] Knopje rekendoor verschijnt op dashboard als wijzingen (positie scenario opslaan)

**To discuss**
- hoe verhoud een interactief element zich tot een tegel?
Zoals in #494  aangegeven. Sandbox interactief element aanmaken -> bij tegel koppelen aan interactief element (of andersom?).

- er wordt per optie aangegeven welke tegel dit betrekking heeft
?? @mattijsstam 
- hardcoded lijstje met optie <-> tegel
?? @mattijsstam 
- elke optie heeft een png gekoppeld met de tegels + highlight
?? @mattijsstam 

- In het geval van dynamische tegels op welk niveau wordt bepaald welke tegels getoond worden?
?? @mattijsstam Tegels zijn niet dynamisch. Ingesteld door CMSer. Relatie tot datamodel en gewoon een PNG uplaoden.

https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/screen/640462b4-6952-4767-9afd-019e6357e7ff/

![image](https://user-images.githubusercontent.com/78690362/227142281-b6ad2326-f07f-4be9-be34-afbc74c36296.png)

**Comment by mattijsstam** [comment]
hoe verhoud een interactief element zich tot een tegel?

- [ ] er wordt per optie aangegeven welke tegel dit betrekking heeft
- [ ] hardcoded lijstje met optie <-> tegel
- [ ] elke optie heeft een png gekoppeld met de tegels + highlight

In het geval van dynamische tegels op welk niveau wordt bepaald welke tegels getoond worden?

**Comment by Erikvv** [comment]
Sandbox pagina is geimplementeerd.
