### ISSUE TITLE
Gebruikers kunnen een scenario opslaan via een URL

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#310]
- [x] Gebruikers kunnen op een knop klikken om een scenario op te slaan vanaf iedere interactievorm (in iedere sectie)
- [x] Gebruikers kunnen het scenario een naam (verplicht) en beschrijving (optioneel) geven
- [x] Gebruikers krijgen een URL die ze kunnen opslaan (notitie, mail, bookmark), delen en via socials (twitter, linkedin, mail) kunnen verspreiden
- [x] Gebruikers kunnen via een URL een scenario inladen
- [x] Gebruikers krijgen terugkoppeling op het ingeladen scenario (nog kloppend?):
    - [x] Toont de gegeven naam van het scenario
    - [x] Toont de gegeven beschrijving van het scenario
    - [x] Wanneer er een interactief element is opgeslagen in de URL die niet meer in de pagina is ingestel
    - [x] Wanneer er interacteive elementen aan de pagina zijn toegevoegd maar die niet zijn opgeslagen in de URL
- [ ] Gebruikers hebben inzicht in de functionaliteit (wat doet het wel en wat doet het niet?) via disclaimers
- [x] Gebruikers kunnen bestaande scenario's niet updaten maar wel vanaf een scenario een nieuwe opslaan (dus een nieuwe URL)

**Comment by mattijsstam** [comment]
- [ ] Link genereren op basis van slider settings
- [ ] Link openen vult sliders in

**Comment by mattijsstam** [comment]
Vragen aan UX

- hoe omgaan met feedbackmodals bij inladen?
- welke data voegt de gebruiker toe aan een link?
- link opent op sectie, holarchie, anders?
- socials delen?
- Op welke manier wordt terugkoppeling gegeven op niet bestaande of nieuwe sliders?
- Hoe geven we aan dat links niet houdbaar zijn? (wijzigingen in sliders, onderliggende scenario's en resultaten)

**Comment by kasperbosman** [comment]
Design gereed: https://xd.adobe.com/view/0466dccb-2b6e-40b2-a726-cec301f32caf-5135/

Scherm 1: Per sectie een button om instellingen binnen een scenario op te slaan.
Scherm 2: Modal scenario opslaan. Naam scenario is verplicht en sceanrio beschrijving optioneel
Scherm 3: Scenario link is gegenereerd en kan gekopieerd worden of gedeeld via mail, linkedin en twitter
Scherm 4: Openen van een scenario met disclaimer nieuwe- of veranderde functionaliteit.

**Comment by broekhuisg** [comment]
Functioneel getest. Heb alle checkboxes nagelopen en het werkt naar behoren! TOP!
