### ISSUE TITLE
Menu items in header disappear when page is not made in Wagtail  

### ISSUE THREAD

**Issue by MariaBee3** [ZEnMo/Holon-webapp#314]
![image](https://user-images.githubusercontent.com/70764188/216038582-d69ddb05-0928-4fb3-8b48-9e4ba20ef26c.png)

When a page is made directly in Pages, the menu items are no longer loaded from Wagtail in the header.

**Comment by pascalalferink** [comment]
The cause: The menu-items are being created with the getPage function in the file **[...path].tsx** All other files in the pages directory are not using this file and function and therefore, they won't contain the navigation.

**Comment by pascalalferink** [comment]
@broekhuisg  made the base for this, I finished it.

On every static page, the content needs to be wrapped in a BasePage. Also every component needs to grab the navigation with the function "getStaticProps". I believe this function can't be made generic https://nextjs.org/docs/basic-features/data-fetching/get-static-props


![Image](https://user-images.githubusercontent.com/13336728/217748424-af5651e4-efd6-443f-bdcc-4858db60f17b.png)
