### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#32]
### Description

In order to track the users that visit holontool.nl google analytics should be implemented along with a cookie popup to enable users to opt out of the tracking cookies.

### To discuss

- Which Google Analytics account do we use, is there a HOLON account?
- What should be the text of the cookie popup?
- Do we need a cookie policy?

### Acceptance criteria

- [ ] When a user opens holontool.nl for the first time in a browser a cookie popup is shown
- [ ] When the user accepts tracking cookies, google analytics is started
- [ ] When the user rejects tracking cookies google analytics is not started
- [ ] Add static cookie policy page with a copy of the witteveenbos text

**Comment by thesethtruth** [comment]
Working on getting google analytics environment set up today

**Comment by mattijsstam** [comment]
@thesethtruth create a simple design of the cookie popup and discuss whith JZ about the text and cookie policy

**Comment by thesethtruth** [comment]
![220628 mockup sprint fuik](https://user-images.githubusercontent.com/78690362/179189910-5ee7b6b1-dd65-4c1a-ac11-e4eff7639e65.jpg)

**Comment by thesethtruth** [comment]
# Cookie Policy

Holontool.nl gebruikt verschillende soorten cookies. Omdat het belangrijk is voor jou als gebruiker hier controle over te hebben, leggen we op deze pagina uit welke cookies we inzetten en voor welk doel. 

## Wat zijn cookies?

Cookies zijn kleine tekst bestanden die een website op jouw computer, tablet of mobiel plaatst wanneer je de website bezoekt. Deze bestanden houden informatie bij over je bezoek op de website. Dit zorgt er bijvoorbeeld voor dat de volgende keer dat je naar dezelfde website gaat, deze je herkent als bekende gebruiker. 

## Welke cookies gebruiken we?

1.  Functionele cookies

    Er worden altijd functionele cookies geplaatst. Deze cookies zijn nodig om de website goed te laten werken.

2.  Niet-functionele cookies

    Naast functionele cookies plaatst holontool.nl ook standaard analytische cookies. Standaard analytische cookies zijn niet-functionele cookies, omdat ze niet noodzakelijk zijn om de website goed te laten werken.

## Analytische cookies

Analytische cookies helpen eigenaren van websites begrijpen hoe bezoekers hun website gebruiken, door gegevens te verzamelen en te rapporteren.

| Naam    | Aanbieder            | Doel                                                                                                                                                                          | Vervaltermijn | Type  |
| ------- | -------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------- | ----- |
| collect | google-analytics.com | Wordt gebruikt om gegevens over het apparaat en het gedrag van de bezoeker naar Google Analytics te sturen. Volgt de bezoeker op verschillende apparaten en marketingkanalen. | Sessie        | Pixel |


## Google Analytics

Deze website maakt gebruik van Google Analytics, een webanalyse-service die wordt aangeboden door Google Inc. (Google). Wij gebruiken deze dienst om bij te houden hoe bezoekers de website gebruiken, met als doel de website te verbeteren. Voor dit doel worden cookies geplaatst. Deze informatie wordt overgebracht naar Google. Google slaat deze gegevens vervolgens op in servers in de Verenigde Staten. Google gebruikt deze informatie om bij te houden hoe onze websites gebruikt worden, om rapporten over de websites aan ons te kunnen verstrekken. Wij hebben Google Analytics privacy-vriendelijk ingesteld. Onder meer wordt het IP-adres gepseudonimiseerd voordat dit gegeven wordt verzonden aan Google. Daarnaast hebben wij met Google een verwerkersovereenkomst gesloten op grond waarvan het Google niet is toegestaan deze gegevens aan derden te verstrekken of voor andere Google-diensten in te zetten. De maximale bewaartermijn van de cookies die middels deze dienst worden gebruikt is door ons ingesteld op 24 maanden. Dit betekent dat na afloop van deze termijn de gegevens niet meer kunnen worden uitgelezen. De verwerking van jouw persoonsgegevens via Google Analytics is gebaseerd op ons gerechtvaardigde belang om algemene statistieken van onze websitebezoekers te verkrijgen.

Lees voor meer informatie het [privacybeleid](https://policies.google.com/privacy?hl=nl) van Google en het [specifieke privacybeleid](https://support.google.com/analytics/answer/6004245?hl=nl) van Google Analytics. Klik [hier](https://tools.google.com/dlpage/gaoptout) voor meer informatie over de opt-out regeling van Google.

## Cookies blokkeren en verwijderen

Je kunt cookies zelf aanzetten of uitzetten in de instellingen van je browser. Meer informatie over het verwijderen en weigeren van cookies vind je op de website van de [Consumentenbond](https://www.consumentenbond.nl/internet-privacy/cookies-verwijderen).

## Over deze cookieverklaring

Holontool.nl mag deze cookieverklaring aanpassen, bijvoorbeeld omdat onze websites of de regels rond cookies wijzigen. Je kunt de actuele versie van deze cookieverklaring raadplegen door onderaan elke pagina te klikken op de link cookieverklaring.

**Comment by thesethtruth** [comment]
Policy can also be found as `.md` file in `frontend/public/md_files/cookie_page.md` in branch [32-google-analytics](https://github.com/ZEnMo/Holon-webapp/tree/32-google-analytics). Perhaps we can render this over at `holontool.nl/cookies` in a similar way that @MariaBee3 has done for privacy?

**Comment by thesethtruth** [comment]
gtag is now included in the next app, via the `next/script` component! 

![image](https://user-images.githubusercontent.com/78690362/179208039-40079290-f7e8-471a-b2db-5e221d90e8b9.png)

**Comment by thesethtruth** [comment]
I checked the GA ID and saw that you correctly initiate that in `gtag.js`.

I can see the GET request the `analytics.js` succeeding: 
![image](https://user-images.githubusercontent.com/78690362/180009991-7e8db36b-6e0d-4f75-96c1-238aa6a5072a.png)

**However**, I don't get information in the ga dashboard, implying that data from the site is not coming through to ga.

I'm not sure whether this could be caused by the warning below but it might be worthwhile to look into this:
![image](https://user-images.githubusercontent.com/78690362/180009491-a4d51617-d55d-4d43-8ff3-f2786995b9dd.png)

Otherwise I don't have any experience using ga, perhaps somebody else from the team does?
