### ISSUE TITLE
User frontend inputs should be applied on the datamodel (scenario builder)

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#322]
Acceptance:

1. Accept all logic and configuration of #324 

![Image](https://user-images.githubusercontent.com/78690362/217535379-705a0a50-9a37-487e-a48f-6fc5e374b46b.png)

**Comment by thesethtruth** [comment]
depends on #401

**Comment by mattijsstam** [comment]
This issue is depentend on merge request #418 and an extension of issue #322 

- [ ] Connect interactive elements to `rules`
- [ ] Remove api module
- [ ] Change API endpoints in the frontend
     - [ ] Kosten en baten 
     - [ ] Dashboard results
