### ISSUE TITLE
Interactive inputs should be able to be configured such that their mapping/scaling logic can be configured in relation to the datamodel

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#324]
- Ability to map interactive inputs to specific parts of the datamodel such as asset atributes

We can create a parent model or link to [generic relations](https://docs.djangoproject.com/en/4.1/ref/contrib/contenttypes/#generic-relations) to control which attribute a interactive input maps to, Or use [django polymorphic](https://django-polymorphic.readthedocs.io/en/stable/) If done well this hierarchy of models will make it easy to fulfill the other requirements because you can filter, group based on the model type.

- Filter functionality for mapping interactive inputs (conditionals)
- The mapping should be able to balance attribute groups (total amount of cars is constant if technology share changes)
- One interactive input should be able to map to multiple filter-and-adjust steps

Acceptance:
- Filter on class and parent(s) class
- Filter on attribute value (=<>!=)
- Adjust values of the filtered results given a range

Example: change the power setting of photovoltaics of all households that have an energy demand greater than 300 kWh to 50% of the maximum power (based on the min/max)

**Comment by mattijsstam** [comment]
![Image](https://user-images.githubusercontent.com/32770108/217543005-ed21b296-a595-41df-b37a-15a1f4fbb83b.png)

**Comment by thesethtruth** [comment]
1. Move scenarios to be a child of the case page model 
2. Interactive elements should be a child of the scenarios
3. Factor/filter fields should be a child of interactive elements
4. Multiple filters can be applied, with their own factor (attribute range)

**Comment by thesethtruth** [comment]
closed by #378
