### ISSUE TITLE
[holarchie] Gebruikers kunnen schakelen tussen het 'tegeloverzicht met dashboard' en het holarchie scherm doormiddel van een tab button

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#329]
To discuss:

- [ ] Wat voor grid hanteren we voor mobile modus? Bijv. de drie verticale kolommen onder elkaar.
--> Drie verticale kolommen is ok!
- [ ] Hoe gaan we om met togglen naar view als storyline content langer is in de linkerzijde.  Voorstel: alleen navigeren tussen secties in 'normaal' view en holarchie openen met tabknop en er overheen tekenen

Acceptance:
- [x] 1/3 per verticale kolom (min marge)
- [x] 1/3 per horizontale rij (min header)
- [x] Grid is van licht naar minder lichtblauw gekleurd met zwarte tekst
- [x] Mobile worden deze kolommen onder elkaar getoond
- [x] Geen scroll (grid staat vast) -> wel scroll in de panelen
- [x] De tabknop voor overschakelen zit aan het begin van iedere sectie (boven de eerste tekst / interactieve elementen) en is sticky aan de bovenkant bij scrollen
- [x] tab naam 1 = interactiemodus (storyline/challenge/sandbox) 
- [x] tab naam 2 = 'holarchie'
- [x] Het 'holarchie' scherm is beschikbaar in iedere sectie en ieder interactie modus via tab knopjes

**Comment by thesethtruth** [comment]
![mock-up_genestheid2](https://user-images.githubusercontent.com/78690362/217762204-63737a11-8924-47fc-8e4b-7a0d1843d6be.jpg)
![mock-up_genestheid1](https://user-images.githubusercontent.com/78690362/217762209-e8f603b5-9dad-44ee-88c3-d7fbe6a68c6a.jpg)

**Comment by MariaBee3** [comment]
Wat voor grid hanteren we voor mobile modus? Bijv. de drie verticale kolommen onder elkaar.

**Comment by MariaBee3** [comment]
Dit is opgelost: dit gebeurde als de content van de pagina te kort was, waardoor de buttons niet helemaal naar boven konden worden gescrolld. Nu wordt de content onder de modal ook schermgroot gemaakt waardoor er genoeg ruimte is om de buttons bovenaan te zetten. Deze class wordt weer verwijderd als je de holarchy modal sluit.
