### ISSUE TITLE
Quality improvements of the backend code

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#33]
### Description

Due to the strict deadline some concessions have been made when it comes to the quality of code and the components developed in the backend. This issue describes the technical debt of the backend with the goal of fixing the issues before we continue the development of additional functionality.

### To discuss

Which items do we want to fix?
- Missing unit tests
- Missing integration (api) tests
- Repetitive logic
- [django coding-style](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/)

### Acceptance criteria

- [x] All custom functions have at least one unit test
- [x] All api endpoints have at least one unit test
- [x] There is no repetitive logic
- [x] Django code follows the django coding-style where applicable

**Comment by mattijsstam** [comment]
| Name                                                                 | Stmts | Miss | Cover | Missing |
|----------------------------------------------------------------------|-------|------|-------|---------|
| -------------------------------------------------------------------- |       |      |       |         |
| backend/settings/production.py                                       | 10    | 10   | 0%    | 1-42    |
| backend/urls.py                                                      | 16    | 16   | 0%    | 16-53   |
| backend/wsgi.py                                                      | 4     | 4    | 0%    | 10-16   |
| holon/anylogic.py                                                    | 41    | 41   | 0%    | 2-122   |
| holon/models/rating.py                                               | 9     | 1    | 89%   | 27      |
| holon/models/update_register.py                                      | 7     | 1    | 86%   | 18      |
| holon/serializers/__init__.py                                        | 2     | 2    | 0%    | 1-2     |
| holon/serializers/rating.py                                          | 6     | 6    | 0%    | 1-7     |
| holon/serializers/update_register.py                                 | 6     | 6    | 0%    | 1-7     |
| holon/tests.py                                                       | 1     | 1    | 0%    | 1       |
| holon/views.py                                                       | 7     | 7    | 0%    | 1-46    |
| holon/viewsets/__init__.py                                           | 2     | 2    | 0%    | 4-5     |
| holon/viewsets/rating.py                                             | 6     | 6    | 0%    | 1-12    |
| holon/viewsets/update_register.py                                    | 6     | 6    | 0%    | 1-8     |
| -------------------------------------------------------------------- |       |      |       |         |
| TOTAL                                                                | 161   | 109  | 32%   |         |

**Comment by mattijsstam** [comment]
black --check --target-version=py35 .
would reformat backend/wsgi.py
would reformat holon/apps.py
would reformat holon/models/update_register.py
would reformat holon/models/rating.py
would reformat backend/urls.py
would reformat holon/migrations/0002_rating_remove_updateregister_rating.py
would reformat backend/settings/production.py
would reformat holon/serializers/rating.py
would reformat holon/migrations/0001_initial.py
would reformat holon/viewsets/__init__.py
would reformat holon/serializers/update_register.py
would reformat holon/viewsets/rating.py
would reformat holon/anylogic.py

Oh no! 💥 💔 💥
13 files would be reformatted, 13 files would be left unchanged.

**Comment by mattijsstam** [comment]
Scope is changed to

- [ ] Writing tests

**Comment by pascalalferink** [comment]
When executing `python manage.py test` I see it renders 7 tests with `OK` as a final result. These 7 tests are in 
- backend/holon/tests.py (5 tests)
- backend/holon/models/tests.py (2 tests)

@mattijsstam , I noticed two things, are these intentional?:
- When removing attributes in the MOCK_REQUEST the test fails, the test passes when I change a value of an attribute.
- When changing MOCK_RESULTS to an empty object , the test still passes.
