### ISSUE TITLE
[holarchie] Content managers kunnen per interactive element aangeven op welk niveau die ingrijpt (nationaal, lokaal en tussenniveau)

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#330]
Discussiepunten:
1. Zijn de drie niveaus hardcoded, of zijn deze ergens te beheren?\
 --> Het onderste en bovenste niveau staan vast (lokaal/model-niveau en nationaal). Het tussenniveau is vrij in te stellen per casus (heeft ook betekenis voor het ETM)

Acceptance:
- [ ] Voor multi/single select kan per optie worden aangegeven over welk van de drie niveaus het gaat
- [ ] Er kan altijd maar 1 niveau per optie of slider geselecteerd worden
- [ ] Slider = 1 niveau
- [ ] Er zijn 3 hardcoded niveaus: Nationaal, tussen, lokaal

**Comment by thesethtruth** [comment]
![image](https://user-images.githubusercontent.com/78690362/217762570-a9241332-456e-4f18-997d-7de2858b2bf0.png)

**Comment by pascalalferink** [comment]
1. Zijn de drie niveaus hardcoded, of zijn deze ergens te beheren?

**Comment by pascalalferink** [comment]
Field 'level' is added on two places in CMS:
- Per interactive Input (see first screenshot)
- Per option within an interactive input option (screenshot 2)

![image](https://user-images.githubusercontent.com/13336728/218053849-97ef89da-58b9-4b9d-bc79-95ab4e98944f.png)
![image](https://user-images.githubusercontent.com/13336728/218053835-8d85f633-d19c-448c-ab8f-c9ee9add832f.png)

**Comment by pascalalferink** [comment]
![image](https://user-images.githubusercontent.com/13336728/218055147-fe67f67b-6d4b-4da1-b8fa-9c2f107a66b9.png)
![image](https://user-images.githubusercontent.com/13336728/218055281-aa9b6603-d1d9-4de1-9af6-a1beee201b25.png)
