### ISSUE TITLE
[holarchie] De afbeelding die zichtbaar is, wordt getoond op basis van condities (zoals in challenge) die overeenkomen met inputs

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#332]
Discussiepunten:
1. kan de conditionele logica aan 1 optie in een slider toegewezen worden, dan kun je deze eenvoudig oplossen door een afbeelding aan een optie mogelijk te maken?
--> Nee, het kan ook van meerder inputs afhankelijk zijn
Acceptance:
- [ ] Afbeeldingen en logica wordt op het niveau van een casus geconfigureerd
- [ ] Meerdere conditionele logica per afbeelding op interactieve input -> hetzelfde als de modal logica
- [ ] Logica is alleen afhankelijk van inputs, niet van kpi's
- [ ] 1 afbeelding is de default (verschijnt als geen condities voldaan worden = achterste laag)

**Comment by thesethtruth** [comment]
![image](https://user-images.githubusercontent.com/78690362/217763192-467b2fd1-80ea-4a63-b0ef-2c0cbef7a27c.png)

**Comment by thesethtruth** [comment]
![image](https://user-images.githubusercontent.com/78690362/217763324-d35ed4a4-6f44-4256-8632-52993dd3d589.png)

**Comment by mattijsstam** [comment]
kan de conditionele logica aan 1 optie in een slider toegewezen worden, dan kun je deze eenvoudig oplossen door een afbeelding aan een optie mogelijk te maken?

**Comment by mattijsstam** [comment]
dependent on #304

**Comment by pascalalferink** [comment]
Base has been made:

- In each section,the moderator can add multiple Holarchy feedback images.
- Each images has one ore more conditions
- these conditions are the interactive inputs

Each time an interactive input changes, it directly checks if a feedback image should be presented.


In the 2 screenshots below you see the admin and the effect it has.

**To do: It needs to be integrated and styled** 



![Image](https://user-images.githubusercontent.com/13336728/218694247-b7f4eb0b-cb5f-4eee-afc6-9e81955c7dd7.png)


![Image](https://user-images.githubusercontent.com/13336728/218695710-d9f858b5-46eb-495c-b0e4-bb2578c59c5f.png)

**Comment by pascalalferink** [comment]
Feature has been developed:

- Based upon the conditions, one image will be shown, 
- If no condition is met, the first holon feedback image will be shown
- if no feedback image is configurated in Wagtail, no image will be shown.

The image will fit in the middle column, 


![Image](https://user-images.githubusercontent.com/13336728/220063957-ef837a01-99a7-49bf-a3b2-4e44bf062f2a.png)
![Image](https://user-images.githubusercontent.com/13336728/220064782-db4a7039-70b6-4868-acc1-8c0aa499fc35.png)
