### ISSUE TITLE
[kosten&baten] Gebruikers kunnen in het kostenoverzicht scherm schakelen tussen het grafiek, tabel en detail scherm

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#335]
![image](https://user-images.githubusercontent.com/78690362/219006551-4c3e75d7-75f3-4e82-a7fd-3b5a3fe7617c.png)

Acceptance:
- [ ] De standaard weergave is grafiek
- [ ] Schakelen tussen schermen met een button-groep boven de grafiek (tabs in headless UI)
- [ ] Namen van tabjes = grafiek, tabel en detail

**Comment by MariaBee3** [comment]
Wordt opgelost in issue #334

**Comment by thesethtruth** [comment]
closed as done in #334
