### ISSUE TITLE
[kosten&baten] De grafiek toont per actor categorie de lasten en baten op een verticale lijn (boven en onder de nullijn) met barplots

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#336]
Design: https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/

To discuss:
1. Hoe gaan we om met meer dan 6 groepen? Laten we aannemen dat de max in ieder geval 15 is. Horizontaal scrolbaar? 

Acceptance:
- [x] Duidelijke nullijn/nettolijn is zichtbaar
- [x] Kosten en baten hebben hun eigen as-label (boven/onder nul) en zijn niet negatief
- [x] Alle groepen hebben een eigen kleur (per soort actor 1 kleur, global dus voor alle casi), als een groep niet bestaat val je terug op een ovallende kleur (oranje)
- [x] Kleuren zijn global in te stellen in het CMS per groep
- [x] Per barplot categorie is er een label boven de grafiek
- [x] Er is een legenda te zien voor de actoren onderin
- [x] Titel boven de grafiek zegt 'kosten en baten per groep' en dus niet segment
- [x] Er is een categorie die heet 'afschrijving' maar die wordt niet geplot als barplot categorie: dus partijen kunnen kosten hebben

nice to have:
- [ ] Een hover verteld van wie naar wie de geld stroom gaat (en is altijd positief); dus `actor` ontvangt 200€ van `actor` OF `actor` betaald 200€ aan `actor`.

![6-2-kostenoverzicht-modal-grafiek](https://user-images.githubusercontent.com/124704207/218788580-266fb07f-7ae1-4321-b3c1-224db7b18f78.png)

**Comment by thesethtruth** [comment]
Dummy data: 
```json
{
  "Huishouden": {
    "Afschrijving": "-60",
    "Huishouden": null,
    "Commercieel bedrijf": "0",
    "Overheidsinstelling": "0",
    "Energieleverancier": "-200",
    "Netbeheerder": "-200",
    "Overheid": "125",
    "Netto kosten": "-335"
  },
  "Commercieel bedrijf": {
    "Afschrijving": "0",
    "Huishouden": "0",
    "Commercieel bedrijf": null,
    "Overheidsinstelling": "0",
    "Energieleverancier": "-200",
    "Netbeheerder": "-100",
    "Overheid": "-50",
    "Netto kosten": "-350"
  },
  "Overheidsinstelling": {
    "Afschrijving": "-20",
    "Huishouden": "0",
    "Commercieel bedrijf": "0",
    "Overheidsinstelling": null,
    "Energieleverancier": "-100",
    "Netbeheerder": "-200",
    "Overheid": "-75",
    "Netto kosten": "-395"
  },
  "Energieleverancier": {
    "Afschrijving": "0",
    "Huishouden": "200",
    "Commercieel bedrijf": "200",
    "Overheidsinstelling": "100",
    "Energieleverancier": null,
    "Netbeheerder": "0",
    "Overheid": "0",
    "Netto kosten": "500"
  },
  "Netbeheerder": {
    "Afschrijving": "-500",
    "Huishouden": "200",
    "Commercieel bedrijf": "100",
    "Overheidsinstelling": "200",
    "Energieleverancier": "0",
    "Netbeheerder": null,
    "Overheid": "0",
    "Netto kosten": "0"
  },
  "Overheid": {
    "Afschrijving": "0",
    "Huishouden": "-125",
    "Commercieel bedrijf": "50",
    "Overheidsinstelling": "75",
    "Energieleverancier": "0",
    "Netbeheerder": "0",
    "Overheid": null,
    "Netto kosten": "0"
  }
}
```

**Comment by mattijsstam** [comment]
implementeren voor 10 kolommen maximaal

**Comment by mattijsstam** [comment]
dummy api implementeren die altijd bovenstaande json teruggeeft
