### ISSUE TITLE
[kosten&baten] Gebruikers kunnen voor huishoudens categorie een detail view beijken met grafiek en tabel per subcategory

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#337]
Design: https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/

Discussiepunten:
1. Zit deze data al in de huidige backend of is dit onderdeel van de technical debt oplossen en daarna de ETM cost module implementeren?
--> Dit is een nieuwe feature die door Quintel wordt ontwikkeld. De datastroom vanaf het endpoint is niet scope van deze feature. We werken dit uit met dummy data. 

To discuss:
- [ ] Hoe maken we duidelijk dat de grafiek/tabel tabs alleen op de detail pagina beschikbaar zijn?

Acceptance:
- [ ] Zelfde eisen als aan grafiek scherm maar met subtypes van huishoudens
- [ ] ~Layout is 50/50 horizontaal~
- [ ] ~Tabel wordt getoond aan de linker kant, grafiek rechts~
- [ ] Onder de tabs komen in het geval van detail nieuwe tabs, die ook weer grafiek/tabel optie geven (andere kleur of onder detail laten vallen? )
- [ ] Grafiek / tabel overzicht is hetzelfde als in de andere pagina's
- [ ] NOTE: hou rekening met ruimte voor een dropdown (huishouden/industrie/energieleveranciers) naast de detail grafiek/tabel switch (toekomst)
- [ ] Data wordt vanuit een andere api opgehaald dan de grafiek en tabel tab

![Image](https://user-images.githubusercontent.com/58260886/221612016-c134d53f-e556-4c8f-92e6-8fb251eea54d.png)

**Comment by mattijsstam** [comment]
Zit deze data al in de huidige backend of is dit onderdeel van de technical debt oplossen en daarna de ETM cost module implementeren?

**Comment by thesethtruth** [comment]
@mattijsstam nog niet in de huidige backend en het is anders dan de kosten module (`im_sorry.py`). Dit is echt een losse functionaliteit.
Hieronder dummy data zodat we kunnen ontwikkelen:
```json
{
  "Huishouden": {
    "Afschrijving": "-60",
    "Huishouden": null,
    "Commercieel bedrijf": "0",
    "Overheidsinstelling": "0",
    "Energieleverancier": "-200",
    "Netbeheerder": "-200",
    "Overheid": "125",
    "Netto kosten": "-335"
  },
  "Commercieel bedrijf": {
    "Afschrijving": "0",
    "Huishouden": "0",
    "Commercieel bedrijf": null,
    "Overheidsinstelling": "0",
    "Energieleverancier": "-200",
    "Netbeheerder": "-100",
    "Overheid": "-50",
    "Netto kosten": "-350"
  },
  "Overheidsinstelling": {
    "Afschrijving": "-20",
    "Huishouden": "0",
    "Commercieel bedrijf": "0",
    "Overheidsinstelling": null,
    "Energieleverancier": "-100",
    "Netbeheerder": "-200",
    "Overheid": "-75",
    "Netto kosten": "-395"
  },
  "Energieleverancier": {
    "Afschrijving": "0",
    "Huishouden": "200",
    "Commercieel bedrijf": "200",
    "Overheidsinstelling": "100",
    "Energieleverancier": null,
    "Netbeheerder": "0",
    "Overheid": "0",
    "Netto kosten": "500"
  },
  "Netbeheerder": {
    "Afschrijving": "-500",
    "Huishouden": "200",
    "Commercieel bedrijf": "100",
    "Overheidsinstelling": "200",
    "Energieleverancier": "0",
    "Netbeheerder": null,
    "Overheid": "0",
    "Netto kosten": "0"
  },
  "Overheid": {
    "Afschrijving": "0",
    "Huishouden": "-125",
    "Commercieel bedrijf": "50",
    "Overheidsinstelling": "75",
    "Energieleverancier": "0",
    "Netbeheerder": "0",
    "Overheid": null,
    "Netto kosten": "0"
  }
}
```

**Comment by kasperbosman** [comment]
Design aangepast, bovenstaande tasks doorgevoerd. Adobe Xd link is geupdatet.
