### ISSUE TITLE
[kosten&baten] De tabel toont de verschillende actor categorieën (op rij/kolom) en de geldstromen daartussen

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#338]
Design: https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/

To discuss:
1. Hoe gaan we om met meer dan 6 groepen? Laten we aannemen dat de max in ieder geval 15 is. Verticaal en horizontaal scrolbaar? -> eerst max 10 kolommen

Acceptance: 
- [x] Nul of null is wit
- [x] Positief is groen
- [x] Negatief is rood
- [ ] ~De diagonaal heeft * als suffix die verwijst naar een tekst onder de tabel "Afschrijvingen"~ Diagonaal blijft leeg
- [x] Verticale dikke lijnen ipv horizontalen
- [x] ~Kolomlabels hebben een hint 'groep' (x-as label)~
- [x] ~Rijlabels hebben een hint 'transactie met (y-as label)~
- [x] Tabel titel is 'Kosten en baten per groep' en dus niet 'geldstromen tussen segmenten'
- [x] Legenda met groen is 'baten', rood is 'kosten' voor de **verticale** groep
- [x] De data heeft niet altijd dezelfde kolomnamen als rijnamen (niet symetrisch) en moet generiek inzetbaar zijn

Nice to have:
- [ ] Hover geeft dikkere lijnen / highlight om aan te geven welke rij / kolom je bent (even kijken wat kan in een standaard module)

![Image](https://user-images.githubusercontent.com/13336728/221500377-92122f66-b765-43e9-a855-d1dfa1f4a70a.png)

**Comment by thesethtruth** [comment]
Dummy data: 
```json
{
  "Huishouden": {
    "Afschrijving": "-60",
    "Huishouden": null,
    "Commercieel bedrijf": "0",
    "Overheidsinstelling": "0",
    "Energieleverancier": "-200",
    "Netbeheerder": "-200",
    "Overheid": "125",
    "Netto kosten": "-335"
  },
  "Commercieel bedrijf": {
    "Afschrijving": "0",
    "Huishouden": "0",
    "Commercieel bedrijf": null,
    "Overheidsinstelling": "0",
    "Energieleverancier": "-200",
    "Netbeheerder": "-100",
    "Overheid": "-50",
    "Netto kosten": "-350"
  },
  "Overheidsinstelling": {
    "Afschrijving": "-20",
    "Huishouden": "0",
    "Commercieel bedrijf": "0",
    "Overheidsinstelling": null,
    "Energieleverancier": "-100",
    "Netbeheerder": "-200",
    "Overheid": "-75",
    "Netto kosten": "-395"
  },
  "Energieleverancier": {
    "Afschrijving": "0",
    "Huishouden": "200",
    "Commercieel bedrijf": "200",
    "Overheidsinstelling": "100",
    "Energieleverancier": null,
    "Netbeheerder": "0",
    "Overheid": "0",
    "Netto kosten": "500"
  },
  "Netbeheerder": {
    "Afschrijving": "-500",
    "Huishouden": "200",
    "Commercieel bedrijf": "100",
    "Overheidsinstelling": "200",
    "Energieleverancier": "0",
    "Netbeheerder": null,
    "Overheid": "0",
    "Netto kosten": "0"
  },
  "Overheid": {
    "Afschrijving": "0",
    "Huishouden": "-125",
    "Commercieel bedrijf": "50",
    "Overheidsinstelling": "75",
    "Energieleverancier": "0",
    "Netbeheerder": "0",
    "Overheid": null,
    "Netto kosten": "0"
  }
}
```

**Comment by mattijsstam** [comment]
@kasperbosman  levert ontwerp aan voor de lijnen

**Comment by pascalalferink** [comment]
work-in-progress

![Image](https://user-images.githubusercontent.com/13336728/221223674-6ed0584e-ae74-4fc5-8754-7da89f5175c6.png)

**Comment by pascalalferink** [comment]
end result

![Image](https://user-images.githubusercontent.com/13336728/221545167-eeb3a831-a83f-45c9-8552-f605d1789c36.png)
