### ISSUE TITLE
Tooltip of the results should change based on the national / local switch when toggled 

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#35]
![image](https://user-images.githubusercontent.com/78690362/178484270-a227a84b-b88a-4f4f-b7ea-a5fc04ea2c12.png)

**Comment by pascalalferink** [comment]
The change was one line of code:
`<Tooltip tooltipMessage={local ? messageLocal : messageNl} result={true}>`

is changed to
`<Tooltip tooltipMessage={local === true ? messageLocal : messageNl} result={true}>`

The prop local is a boolean, so it is always present (and therefore always returns true). The condition is now changed. 

@MariaBee3  reviewed it locally
