### ISSUE TITLE
[challenge] Content managers should be able to turn off confetti for pop-up modals

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#350]
Because it might be too much sometimes

**Comment by pascalalferink** [comment]
![image](https://user-images.githubusercontent.com/13336728/219023000-2dcd9392-1694-4c9f-9f21-8373d0b656c8.png)

![image](https://user-images.githubusercontent.com/13336728/219023744-297f4686-78be-4fd5-abad-73030996d6e1.png)

**Comment by thesethtruth** [comment]
Zoooo dan! Snel gedaan deze :rocket:
