### ISSUE TITLE
[challenge] If the conditions that the modal is based on only relies on inputs, the modal should be configurable to appear after user input

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#351]
Perhaps a 1/2 second delay would make most sense (in line with the delay of the input to API call)

**Comment by pascalalferink** [comment]
I understand the question, but how to deal with the following:

The moderator has made two modals:
- Modal 1 appears when local netload > 123456
- Modal 2 appears when slider solarpanels > 50

When the user drags the slider to 68, directly (after .5sec) the second modal appears. In the mean time, the api-call is handled and after a few seconds there is the response with a local netload > 123456. In theory the first modal should appear, but the other modal is also present.

What to do?
My suggestion: I think responding to the input is only a good idea when all the inputs of all feedbackmodals on the page  respond to the inputs.

**Comment by thesethtruth** [comment]
@pascalalferink 
> My suggestion: I think responding to the input is only a good idea when all the inputs of all feedbackmodals on the page respond to the inputs.

Agreed. Lets discuss how to best implement this. Or just list the implications and give that back to those that provided this feedback?

**Comment by thesethtruth** [comment]
No longer needed as caching is implemented
