### ISSUE TITLE
Content managers can filter on discrete series (i.e. A,B,C,D) with interactive element mapping

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#357]
Acceptance:
- [x] Filter on text choices for that attribute (conditional choices, i.e. if user selects the energy label attribute then take the `EnergyLablEnum`)
- [x] Data certainty: custom `clean` function that validates based on fields
- [x] Usability: give feedback in the Django admin
- [x] Nice to have: compare text choices based on ranking (greater or less than) of the text choices
- [x] Configure in CMS the discrete value options

**Comment by SCHS13** [comment]
@thesethtruth Is there a list of textchoices classes that have a ranking and are they already in the right order?

**Comment by thesethtruth** [comment]
in `gridconnection.py`

```python
class InsulationLabel(models.TextChoices):
    A = "A"
    B = "B"
    C = "C"
    D = "D"
    E = "E"
    F = "F"
    G = "G"
    NONE = "NONE"
```
