### ISSUE TITLE
In holarchy-tab, the popover is not shown properly

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#377]
In the interactive modus, the popover is shown as intended. except in the holarcy-view the popover isn't show properly (see screenshot below)

![Image](https://user-images.githubusercontent.com/13336728/221164812-e6344fa1-2683-4439-9d3e-c62f08f14b65.png)

**Comment by mattijsstam** [comment]
Conclusie: Popovers in holarchie tab weglaten
