### ISSUE TITLE
Labels of the corresponding level are not shown at the interactive input side

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#383]
![image](https://user-images.githubusercontent.com/78690362/221905069-79e8ea9c-2e06-4b6d-9861-bf7a67dd4f03.png)

**Comment by pascalalferink** [comment]
Labels have been added:
![image](https://user-images.githubusercontent.com/13336728/222087468-1041426a-8678-4690-b528-ca2d008840f2.png)
