### ISSUE TITLE
Applying more than one interactive condition on the feedback image yields an app client side error

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#385]
Cause of the issues is found: interactive element was not present on the canvas. 

Proposed fix: make sure the error does not lead to a fatal clientside crash. Add a help text at the feedback image object that notes that elements should be present at the storylinesection in wagtail.

![image](https://user-images.githubusercontent.com/78690362/221906246-bca002d5-4c66-48b7-ab87-80707a6b5509.png)

**Comment by pascalalferink** [comment]
Fallback has been made, also en extra help text is added 
_Please make sure the parameter is present in this section. Otherwise you assert something that doesn't exist_




![Image](https://user-images.githubusercontent.com/13336728/222425175-d6868505-4e89-49ce-ad74-65dea747d501.png)
