### ISSUE TITLE
The colored sections behind the image should be shown as straight lines and not as angled elements

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#388]
![image](https://user-images.githubusercontent.com/78690362/221909274-e2a75221-903e-453d-9448-8613e64c6a83.png)

**Comment by mattijsstam** [comment]
nice to have: witte vlak opvullen met leeg dashboard

**Comment by mattijsstam** [comment]
rode lijn wordt doorlopende stippellijn

**Comment by kasperbosman** [comment]
@pascalalferink Achtergrondkleuren: https://xd.adobe.com/view/96b4b2dd-2d3a-4fa5-aa84-64d742453e9f-c3e7/

**Comment by pascalalferink** [comment]
- background colors have been implemented
- after discussion with @kasperbosman  the dashed border is removed 
- Right column center row has background color and feedback that no data is present


![Image](https://user-images.githubusercontent.com/13336728/222450138-5d3a9586-364a-408c-9253-82025de20b1d.png)
