### ISSUE TITLE
Hover in kostengrafiek per staafje ipv kolom

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#395]
Zie design voor labels: deze moeten per staafonderdeelbalkje worden getoond zonder kleur

**Comment by pascalalferink** [comment]
![image](https://user-images.githubusercontent.com/13336728/222406027-dadf19ec-e471-4af0-9d75-538ee0fac294.png)

![image](https://user-images.githubusercontent.com/13336728/222406105-edc39fef-78b6-401f-9be9-1b7556fc9b99.png)
