### ISSUE TITLE
Filter, rules and values should be set at the option level for single select

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#431]
Acceptance
- [ ] Multiple filter, rule and value per option 
- [ ] Continuous element should remain functional

**Comment by TAVMWB** [comment]
todo:
- [ ] Hang `scenario_rule` onder `InteractiveElementOptions` of `InteractiveElementContinuousValues` ( 2 foreign keys, ééntje ingevuld)
- [ ] make sure `rule_mapping` still works with new structure (add extra loop in `get_scenario_and_apply_rules(..)`)
