### ISSUE TITLE
Connect new api endpoint to dashboards in storyline page

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#450]

**Comment by pascalalferink** [comment]
new api call has been connected, I notice the following:

1. The intermediate level is present in the api-call, but the radio button is missing in the storyline view. should it be there?
2. Each time the api call is fired, also costBenefit is updated, is this necessary? 
3. See first screenshot: the amount of euro's at affordability: is it presented as intended?
4. In the costBenefitModal data seems to be missing: some data is a property with a category, but not as a category itself. (screenshot 2)



![Image](https://user-images.githubusercontent.com/13336728/225601318-df24dbf7-0a00-4718-81d2-0e0b36a4ea68.png)



![Image](https://user-images.githubusercontent.com/13336728/225603783-6593cc02-460f-4b92-b724-b026e24815be.png)

**Comment by pascalalferink** [comment]
Radio button has been added:


![Image](https://user-images.githubusercontent.com/13336728/225621288-99f03b5b-a024-4017-882b-07c2d52ad292.png)
