### ISSUE TITLE
Performance of `get_scenario_and_apply_rules` is very poor on large datamodels

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#467]
- [ ] Label `reference_scenario` (ook chill voor niet laten zien in CMS)

Test with [TVW fixture](https://github.com/ZEnMo/Holon-webapp/blob/cbc1a550a4362eff791f3484be1fef14699130eb/src/holon/fixtures/datamodel-tvw-fixture_clean_keys.json)

Response (without any other functionality enabled [see below]) takes about **40 seconds** to complete. Tested with:

```python
import requests

r = requests.request(
        method="POST",
        url="http://localhost:8000/wt/api/nextjs/v2/holon/",
        json={"interactive_elements": [], "scenario": 321001},
    )

print(f"Total time elapsed: {r.elapsed.total_seconds()}")

```

##### holon.py view without other functionality 

```python
class HolonV2Service(generics.CreateAPIView):
    serializer_class = HolonRequestSerializer

    def post(self, request):
        serializer = HolonRequestSerializer(data=request.data)

        try:
            if serializer.is_valid():
                data = serializer.validated_data

                scenario = rule_mapping.get_scenario_and_apply_rules(
                    data["scenario"].id, data["interactive_elements"]
                )

                # TODO hand over the original_scenario for configs and the edited scenario for datamodel
                original_scenario = Scenario.objects.get(id=data["scenario"].id)
                # cc = CloudClient(original_scenario)
                # cc.run()

                # cost_benefit_results = CostBenedict(
                #     actors=cc.outputs["actors"]
                # ).determine_group_costs()

                # results = Results(
                #     scenario=scenario,
                #     anylogic_outcomes=cc.outputs,
                #     inter_upscaling_outcomes=DUMMY_UPSCALE,
                #     nat_upscaling_outcomes=DUMMY_UPSCALE,
                #     cost_outcome=DUMMY_COST,
                #     cost_benefit_detail=cost_benefit_results,  # TODO: twice the same!
                #     cost_benefit_overview=cost_benefit_results,  # TODO: twice the same!
                # )

                # Delete duplicated scenario
                scenario.delete()
                return Response(
                    "test done",
                    status=status.HTTP_200_OK,
                )

            else:
                return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response(f"Something went wrong: {e}", status=status.HTTP_400_BAD_REQUEST)



```

**Comment by thesethtruth** [comment]
It's difficult to make a general statement about the relative performance of SQL and Django ORM for resolving recursive data queries since performance can vary depending on a number of factors, such as the specific query being executed, the size of the data set, and the resources available to the database and application server.

That said, SQL is generally optimized for querying and manipulating data, and it's often the case that direct SQL queries can be more efficient than using a higher-level ORM like Django's. Recursive queries in particular can be quite complex to implement in an ORM, and may involve multiple queries or expensive joins that can be streamlined in SQL.

However, it's important to note that using direct SQL queries can also have downsides, such as increased complexity and reduced portability. Additionally, Django's ORM provides a number of features and conveniences that can make development faster and easier, even if they come at the cost of some performance.

Ultimately, the best approach will depend on the specific requirements of your project and the resources available to you. It may be worth experimenting with both approaches to see which works best for your use case.

**Comment by thesethtruth** [comment]
There are several techniques you can use to speed up recursive data queries using the Django ORM. Here are a few suggestions:

    Use prefetch_related() or select_related(): The prefetch_related() and select_related() methods can be used to reduce the number of database queries required to fetch related objects. For example, if you have a recursive relationship between objects, you can use prefetch_related() to fetch all related objects in a single query, rather than executing a separate query for each related object.

    Use annotate() and Subquery(): The annotate() method can be used to annotate each object with information about its related objects. You can then use Subquery() to perform a subquery on the annotated information to retrieve the desired result. This can reduce the number of queries required to fetch the data.

    Use CTE (Common Table Expressions): CTEs are a feature of SQL that allow you to define a named temporary result set that can be referred to within a single SQL query. You can use CTEs to define a recursive query that traverses the hierarchy of related objects and returns the desired result. Django supports CTEs through the With() expression.

    Use database indexes: Ensure that you have the appropriate database indexes set up for the recursive query. This can significantly improve performance by reducing the number of rows that need to be scanned.

    Reduce the depth of recursion: Consider whether it's necessary to fetch all related objects recursively, or whether you can limit the depth of recursion to reduce the amount of data being fetched. This can improve performance and reduce memory usage.

    Cache results: If the recursive data query is executed frequently and the data is relatively static, consider caching the results using a caching framework like Django's built-in caching framework or a third-party caching library like Redis. This can reduce the number of queries required to fetch the data and improve performance.

These are just a few of the techniques you can use to speed up recursive data queries using the Django ORM. The best approach will depend on the specifics of your use case and the resources available to you.

**Comment by thesethtruth** [comment]
Voorstel Matthias: altijd een paar scenario achter de hand hebben klaarstaan

**Comment by TAVMWB** [comment]
Voorstel versnellen interactieve elementen: django caching
caching kan ook helpen met het clonen van scenarios

**Comment by TAVMWB** [comment]
Voortgang vorige week (en gemerged met de main):
Scenario deleten wordt nu async gedaan, dit scheelt 80% van de tijd voor de TVW fixture (endpoint 5x zo snel). 
Clonen is naar gekeken, scenario & children prefetchen geeft 10% versnelling, verder geexperimenteerd met polymorphic's bulk_create maar dit bleek niet te werken als gedocumenteerd.

**Comment by Erikvv** [comment]
Is opgelost.
