### ISSUE TITLE
Verhaallijn crashes to application error

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#484]
Occurs when content managers add a feedbackmodal with incorrect settins

![image](https://user-images.githubusercontent.com/78690362/226368988-816b31b7-65a5-4f1c-9388-f890eabb0187.png)

**Comment by broekhuisg** [comment]
@thesethtruth Het lukt mij niet om deze bug te reproduceren. Heb je een voorbeeld op acc/test/prod waar dit gebeurd?

**Comment by broekhuisg** [comment]
@thesethtruth Bump. Zie mijn vorige comment: "Het lukt mij niet om deze bug te reproduceren. Heb je een voorbeeld op acc/test/prod waar dit gebeurd?"

**Comment by broekhuisg** [comment]
@thesethtruth Ik heb het probleem gevonden en het zit hem voornamelijk in dat de betreffende pagina niet goed is gevuld. De interactive inputs zijn niet geset, iets wat via het CMS niet mogelijk is. Ik denk dat dit is gebeurd bij het uitvoeren van fixtures, want als je dit via het CMS probeert, krijg je een error en kan je dat niet opslaan.

Ik heb een aantal fixes in de front- en backend gedaan (nu nog in review) waarbij de applicatie niet volledig crashed in deze situatie.



![Image](https://user-images.githubusercontent.com/58260886/231459892-382deb13-eab4-4bcb-bf85-b88e920d0b08.png)

**Comment by thesethtruth** [comment]
Super, thanks! Goed onderzoek en fijn dat je ervoor zorgt dat het niet
meer kan gebeuren.
