### ISSUE TITLE
Legenda en kleine updates holarchie

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#492]
- [ ] Tabknopjes stijlen als in design
- [ ] Legenda toevoegen (per casus)
- [ ] Knop met pop-down
- [ ] Twee kolommen; type lijn en type kleur
- [ ] Instelbaar in CMS; label en png 
![image](https://user-images.githubusercontent.com/78690362/227143354-9425a450-5c3d-4841-b152-c0b72927dde8.png)
https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/screen/61e8d154-43b7-40a4-9de1-18bf32ad03a1/

**Comment by pascalalferink** [comment]
Op welk niveau moet deze ingericht worden?
