### ISSUE TITLE
 Content managers kunnen tegels instellen

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#494]
Acceptance:

CMS -> standaard tegels aanmaken als snippets
  - [ ] Afbeelding kiezen per tegel (standaard formaat)
  - [ ] Achtergrond afbeeldingen kunnen toeveogen (standaard formaat)
  - [ ] Hover/Highlight tegel i.r.t. achtergrondafbeelding kunnen instellen (dus: welke achtegrond afbeelding licht op samen met de tegel?)

CMS sandbox
- [ ] Naam van de tegel kunnen geven
- [ ] Kan per tegel interactieve elementen instellen (andere soort snippet) -> voor nu op dezelfde manier configureren als interactieve elementen in storylines
- [ ] minimaal 1 max 16 tegels toevoegen aan een sandbox

**To discuss**

1. wat is het doel van de achtergrondafbeelding, staan hier ook tegels op of komt deze achter de tegels?
Het toevoegen van extra graphics die achter de tegels getoond worden. Zie voorbeeld:

![Image](https://user-images.githubusercontent.com/78690362/227208668-e5a6f8a8-3d53-4ed8-9520-917c0caea896.png)

2. waarom de configuratie instellen, grid kan ook dynamisch getoond worden obv aantal gekozen tegels?  

Omdat je dan een slim algoritme moet maken en de keuze wegneemt bij de content manager. 

4. ik snap niet direct wat er met de geen snippet optie bedoelt wordt, zijn die nieuwe interactieve elementen of is dit een slechts een foreign key koppeling met een bestaand interactief element vergelijkbaar met de storyline?

Nieuwe elementen die alleen geldig zijn binnen 1 casus en alleen binnen de sandbox gebruikt kunnen worden.

6. kan een sandbox interactief element aan meerdere tegels hangen

Mogelijk wel ja. Als dezelfde logica en naamvoering binnen meerdere tegels toepasbaar is, kan dat wel zo handig zijn.

https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/screen/b0552878-2bbe-439b-b96c-3630929f60fc/

Zie demo Pascal https://holontool.nl/tiles-demo/
![image](https://user-images.githubusercontent.com/78690362/227144267-090a84bc-b011-4355-8c7b-5a7fb0f547e7.png)

**Comment by Erikvv** [comment]
Dynamische tegels gaan we niet meer doen.
