### ISSUE TITLE
Gebruikers kunnen een tegel aanklikken voor de instelmodal

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#495]
Acceptance
- [ ] On hover: andere tegels dof / highlight die tegel (met achtergrond afbeelding) (toon naam van tegel als tooltip)
- [ ] On click: Open modal
- [ ] Modal bestaat uit: Naam, tegel afbeelding, sluiten van modal, reset knop en natuurlijk de instellingen
- [ ] Bovenaan staat altijd de participatie aan holonen slider -> voor content manager
- [ ] I'tje per interactief element -> Titel en tekst in popover
- [ ] Rendert de interactieve elementen (SANDBOX) van die tegel
- [ ] Tabjes zijn out-of-scope voor nu 
- [ ] Verticaal scrollbaar
- [ ] Reset knop zet alle instellingen van de sliders terug naar de CMS defaults

![image](https://user-images.githubusercontent.com/78690362/227144455-533f4938-8456-4c6e-a2d1-aee8e020cee3.png)

![image](https://user-images.githubusercontent.com/78690362/227144482-d582b8a0-d957-45a0-b4c7-b7b27e3b2e34.png)
https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/screen/83ce4500-b71e-4ddc-aa5f-bf7eae201067/

**Comment by Erikvv** [comment]
Dynamische tegels gaan we niet meer doen.
