### ISSUE TITLE
`Apply_rules` werkt niet

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#496]
Waarschijnlijk vanwege het ontbreken van de contracten. 

Testen kan op deze [fixture](https://github.com/ZEnMo/Holon-webapp/blob/main/src/holon/fixtures/merged-datamodel-ehub-config-fixture.json)

**Comment by SCHS13** [comment]
Contracten worden nu gedupliceerd en komen ook met de serializer mee. De initiele foutmelding is daarmee nu opgelost.
Nu krijg ik de volgende:

> "Something went wrong: status: FAILED, message: {\"type\":\"INTERNAL\",\"message\":\"IndexOutOfBoundsException: Index 0 out of bounds for length 0\",\"details\":[\"java.lang.**IndexOutOfBoundsException: Index 0 out of bounds for length 0**\",\"\\tat java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)\",\"\\tat java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)\",\"\\tat java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)\",\"\\tat java.base/java.util.Objects.checkIndex(Unknown Source)\",\"\\tat java.base/java.util.ArrayList.get(Unknown Source)\",\"\\tat base.**KpiVisuals.f_plotAgents(KpiVisuals**.java:953)\",\"\\tat base.KpiVisuals.onStartup(KpiVisuals.java:1590)\",\"\\tat com.anylogic.engine.Agent.d(Unknown Source)\",\"\\tat com.anylogic.engine.Agent.start(Unknown Source)\",\"\\tat base.Main.add_kpiVisuals(Main.java:2341)\",\"\\tat base.Main.onStartup(Main.java:6369)\",\"\\tat com.anylogic.engine.Agent.d(Unknown Source)\",\"\\tat com.anylogic.engine.Agent.start(Unknown Source)\",\"\\tat com.anylogic.engine.Engine.start(Unknown Source)\",\"\\tat com.anylogic.cloud.executor.connector.ExperimentSimple.run(ExperimentSimple.java:105)\",\"\\tat com.anylogic.cloud.executor.connector.ExperimentSimple.startRun(ExperimentSimple.java:221)\"]}"

Iets bij de kpi visuals gaat niet goed

Hieronder heb ik nog de JSON die gemaakt wordt als scenario serialized is.
[scenario.txt](https://github.com/ZEnMo/Holon-webapp/files/11059710/scenario.txt)

**Comment by GillisHommen** [comment]
De data in de scenario.txt die hierbij staat is niet consistent; veel velden die een foreign-key zouden moeten zijn, bevatten een incorrecte string, waardoor de links tussen verschillende objecten in het anylogic model niet tot stand komen. (de 'andere kant' van de link kan niet gevonden worden)
Bijvoorbeeld gridconnections hebben een veld parent_electric, die verwijst naar gridnodes. De parent_electric staat in deze data steeds op "E2", terwijl de gridnodes als id "E21" en "E22" hebben. Ook het attribuut "owner_actor" van de gridnodes zelf bevat een incorrecte verwijzing. (staat verwijzen ze naar "ope1", terwijl dat "ope118" zou moeten zijn.
