### ISSUE TITLE
Gebruikers kunnen tegels aanpassen in de sandbox modus

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#497]
- [ ] Tegels krijgen groen kleur filter als aanpassingen zijn gedaan op die tegel
- [ ] Alleen als reset dan wordt tegel weer normale kleur

https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/screen/640462b4-6952-4767-9afd-019e6357e7ff/

![image](https://user-images.githubusercontent.com/78690362/227142281-b6ad2326-f07f-4be9-be34-afbc74c36296.png)

**Comment by Erikvv** [comment]
Dynamische tegels gaan we niet meer doen.
