### ISSUE TITLE
`CostBenedict` should work on the contract list result

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#501]
To do:
- [x] Coupling to ETM module
- [x] Contract list
- [x] Query per group
- [x] Query per subgroup
- [x] Generice implementation

**Comment by noracato** [comment]
De netwerkkosten voor de netbeheerders (afschrijving) komen straks uit de ETM module. Maar hoe weten we wie de "netbeheerder" actoren zijn waar we deze afschrijving op moeten doen. En hoe weten we welke etm-configuratie/query daarbij hoort?

Bij kosten queries die vervolgens met een `convert_with` aan assets worden gelinkt kunnen we herleiden wie de eigenaren zijn. Maar netwerkkosten hebben dacht ik geen asset (toch?). Als dat zo is is het bijvoorbeeld een idee om altijd twee _vaststaande_ actoren/actorgroepen te hebben - één voor netbeheerders en één voor de overheid - plus de mogelijkheid om een actor (of actorgroep) te kunnen linken aan een etm kosten query.

**Comment by thesethtruth** [comment]
Closed by https://github.com/ZEnMo/Holon-webapp/pull/588
