### ISSUE TITLE
Feedback modals do only float comparison and not strings

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#502]
If I have this figured out, this is the case for both the challenge and the holarchy feedbackwindows.

Please verify the following bug report:
> 3.	Interactieve elementen van het type Choice Singleselect werken soms wel maar meestal niet.
In https://holontool.nl/casus-overzicht/bedrijventerrein-energy-hub/bedrijventerrein-energy-hub-uitdaging/ hebben we verschillende van deze elementen geplaatst en alleen met de bovenste (slim laden) lukte het om een modal aan te sturen. Met de andere lukte dit niet, als we die gebruikten als interactive input condition voor een modal, dan werd de modal helemaal niet meer getoond, ook niet als aan alle input conditions voldaan werd. Wat nou het verschil was tussen die elementen heb ik niet kunnen ontdekken. 
> 4.	Als workaround hebben we geprobeerd om de interactieve elementen van het type Choice Singeselect dan maar Multiselect te maken maar dan heb je hetzelfde probleem: de eerste (slim laden) doet het wel, de rest niet. 
>5.	Als workaround hebben we ook geprobeerd om een interactief elementen van het type Choice Singeselect dan maar Continuous te maken en dat werkt wel! We hebben van non-firm ATO, wat eigenlijk een singleselect zou moeten zijn, een slider gemaakt waarbij we de afspraak maakten “hoger dan 50 betekent JA”. Resultaat was goed

**Comment by pascalalferink** [comment]
I think I found the cause. Below are a few srcreenshots:

1. the actual page
2. the api-response with highlighted the **Slim Laden radio** (left side: the interactive input, the right side the feedback modal)
3. The api-response with highlighted the **Bedrijventerrein - energy hub"** which doesn't work (left side: the interactive input, the right side the feedback modal)

In the feedbackmodal, it tries to match the value of the condition with the value of the radio/checkbox. In the third screenshot you can see, it tries to match "AAN" with "0" or "1". This will never be the case, 



![Image](https://user-images.githubusercontent.com/13336728/227896061-ee7b4d5e-09ae-42eb-ae3a-eb5d2b0a51ab.png)



![Image](https://user-images.githubusercontent.com/13336728/227897365-a2319a4e-a394-40bb-bf56-55d2d4ecd91e.png)



![Image](https://user-images.githubusercontent.com/13336728/227897743-5d35e321-8057-47ab-9b81-f9d2d9522ae3.png)

**Comment by mattijsstam** [comment]
Checken of als zowel de optie als de value van de model een string zijn de modal getoond wordt

**Comment by mattijsstam** [comment]
wanneer tekst wordt ingevoerd maar niet gelijk aan wordt gekozen crasht de applicatie niet
