### ISSUE TITLE
Suffix of interactive elements should be configurable

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#504]
Currently is fixed to %, which is kind of weird since the range can be changed by the content managers (but why would you if it is always percentage?)

Should be able to be set by content manager (based on snippet?)

For instance:
- `#` (number of ... cars, heatpumps, etc)
- `MW` 
- `kW`
- `\degC`

**Comment by MariaBee3** [comment]
It is now possible to add a unit type through a snippet. Here you can add the name of the unittype and the symbol: 


![Image](https://user-images.githubusercontent.com/70764188/227505855-c12be840-fcd9-4d90-8a6a-42f7fc7f6107.png)

These can be selected when making an interactive element. 

The frontend will show the symbol of the unit next to the slider. If no unit type is selected the default is %.

**Comment by thesethtruth** [comment]
> It is now possible to add a unit type through a snippet. Here you can add the name of the unittype and the symbol:
> 
> ![Image](https://user-images.githubusercontent.com/70764188/227505855-c12be840-fcd9-4d90-8a6a-42f7fc7f6107.png)
> 
> These can be selected when making an interactive element.
> 
> The frontend will show the symbol of the unit next to the slider. If no unit type is selected the default is %.

Awesome! Love the bloppies 🍐 🍐
