### ISSUE TITLE
Radio buttons / checkboxes seem to deselect in production?

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#506]
Observation: 
Although a default is supplied, none are selected. 

When scrolled to the next section and clicked, the radio group in the previous section is deselected.

**Comment by pascalalferink** [comment]
Issue was found by Jorrit van den Houten, I am looking together with him to this issue

**Comment by pascalalferink** [comment]
Jorrit couldn't recognize the issue. He sent me throught to Peter Hoogeveen, who I contacted via mail

**Comment by pascalalferink** [comment]
Also Peter didn't recognize the issue
