### ISSUE TITLE
Update homepage to remove the russion gas tool

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#51]

**Comment by pascalalferink** [comment]
@thesethtruth , something like this?
![image](https://user-images.githubusercontent.com/13336728/180007552-0188494b-497a-45fc-9c4f-d577245469f8.png)

**Comment by pascalalferink** [comment]
I spoke to @thesethtruth  about this: 
_Prima voor nu. Later krijg ik meer info over hoe het alternatief eruit moet zien; dat zal ik dan verder communiceren. Voor nu kan je dit gewoon naar main mergen en meenemen in de deploy!_
