### ISSUE TITLE
Waardes op het KPI dashboard moeten afgerond worden naar 1 decimaal

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#523]
waardes: 

Netbelasting
102.35648599989024
Betaalbaarheid
50.10831869377574
Duurzaamheid
0.21533489818170112
Zelfvoorzienendheid
27.3597172484791

![Image](https://user-images.githubusercontent.com/32770108/228227126-a2609fc9-3ca1-48b8-abf4-4d56de6a6683.png)

**Comment by MariaBee3** [comment]
![Image](https://user-images.githubusercontent.com/70764188/228263435-7cfa8c13-7b58-4029-b61b-ef9d5a326a39.png)

**Comment by MariaBee3** [comment]
@mattijsstam Moeten de getallen van 'Betaalbaarheid' nog steeds afgerond worden op miljoenen (nationaal) en duizenden (lokaal)? Want dan krijg je nu dus bijv. 0 bij 'Betaalbaarheid'.

**Comment by MariaBee3** [comment]
> @MariaBee3 nationale kosten komen in miljarden uit het ETM volgens mij. Gebiedskosten zouden orde-groottes miljoenen moeten zijn volgens mij, dus afronden naar duizenden is ok. Ik denk dat de getallen die we nu krijgen niet representatief zijn.

Ow ja, ik bedoelde miljarden. Ok, dat zou het zo goed moeten staan. Maak ik er een PR van.
