### ISSUE TITLE
Requested interactive element features

### ISSUE THREAD

**Issue by TAVMWB** [ZEnMo/Holon-webapp#539]
Bij het configureren van het CMS voor het opzetten van casussen en interactive elementen zijn er nog enkele feature requests opgedoken en bij gekomen. Deze issue is een verzameling van deze gevraagde features voor latere refinement.

**Comment by TAVMWB** [comment]
- [ ] ChangeAttributeRuleAction optie voor een vaste waarde ipv interactive element waarde
- [ ] Value van interactive element kunnen wijzigen (schalen, optellen, aftrekken, etc.) (y = ax + b per rule)
- [ ] Skip en Take voor filter (ook afhankelijk van factor) 
- [ ] Random selectie voor filter ipv alleen eerste paar (random take) met vaste seed
- [ ] Volgorde van rules/rule actions/interactive elements kunnen vaststellen/veranderen

**Comment by GillisHommen** [comment]
Een feature die ook erg wenselijk is vanuit debugging ookpunt, is het inzien van de anylogic-input nadat de manipulaties van de sliders zijn toegepast op het referentiescenario. Ofwel, een endpoint zoals deze, maar dan met de aanpassingen van de sliders er ook in: 
https://holon-v2-acceptatie.azurewebsites.net/wt/api/nextjs/v2/datamodel/1/

**Comment by JorritvandenHouten** [comment]
Nieuwe bug: De volgorde van opties onder single select interactieve elementen kan je wijzigen, maar dit wordt niet 'opgeslagen'. Bij opnieuw openen staan ze weer op volgorde van toevoegen (niet fatal, wel vervelend)

**Comment by Erikvv** [comment]
Alles wat hier staat is volgens mij gedaan, zo niet graag een specifiek issue openen.
