### ISSUE TITLE
Met een checkbox salderen afschaffen (tax contracten vervangen)

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#563]
'Een mulit-select box maken met 1 optie. 

'Lijkt mogelijk met het CMS, maar templates voor contracts lijken niet te werken. Verder staan in de Django omgeving honderden contracten. En contracten kunnen geen naam meegegegven worden. Daardoor kunnen we niet bijhouden wat er gaande is.

**Comment by Erikvv** [comment]
Dit lijkt me opgelost maar als hier nog iets niet goed is hoor ik het graag van @PeterHogeveen
