### ISSUE TITLE
2e orde relation fields toepassen

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#569]
Pas alle chemical heat   conversion assets aan van house_gridconnections van gridnode E14

Workaround: gebruik   parent_electric met hardcoded waarde. NIET ROBUUST OMDAT VELDWAARDEN IN CMS   NIET STATISCH ZIJN

**Comment by TAVMWB** [comment]
was aangegeven als nice to have als er omheen te werken is

**Comment by mattijsstam** [comment]
checken met Jorrit of workaround mogelijk is

**Comment by mattijsstam** [comment]
wanneer casus jorrit vervalt ivm deadline dan vervalt ook deze issue

**Comment by SCHS13** [comment]
Closed by #596
