### ISSUE TITLE
afbeeldingen van genestheid in holonen worden nog niet getoond

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#574]
Checken bij Emiel voor reproduceren

**Comment by pascalalferink** [comment]
voorbeeld: https://pizzaoven.holontool.nl/casus-overzicht/bedrijventerrein-energy-hub/tester-holarchie

**Comment by pascalalferink** [comment]
For FeedbackModals it already worked, but this functionality was never built for feedback images.
The change is implementend:

Screenshot 1: configuration in Wagtail
Screenshot 2: the result


![Image](https://user-images.githubusercontent.com/13336728/232423987-44f604f3-0ebe-4f8e-a061-6dd8772602c6.png)

![Image](https://user-images.githubusercontent.com/13336728/232424123-c0a07645-d278-488e-b6cc-46cf40442700.png)

**Comment by pascalalferink** [comment]
A bug is found in this issue by @MariaBee3 : Holarchy Feedback images and Challenge feedbackmodals won't work with multiselects. 
I have created a new issue for it ( #635 )
