### ISSUE TITLE
Secties afhankelijk van de voorgaande secties

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#575]
In de huidige opzet stuurt elke sectie onafhankelijk van de andere secties data op. Dit levert de modelleurs veel werk op omdat ze per sectie alle sliders (ook verborgen) moeten configureren om het goede resultaat op te halen terwijl sommige sliders ook al in voorgaande secties staan.

De wens is om aan een slider een target value mee te kunnen geven, deze target value wordt in alle opvolgende secties gebruikt om de waarde mee te geven.

Wijzigingen in de code:

- [ ] Bij het opbouwen van de request alle sliders van vorige en huidige sectie doorlopen
- [ ] Checken of het de huidige sectie of voorgaande sectie is
- [ ] Wanneer voorgaande sectie en target value -> deze toevoegen aan een key value Set (slider_id: value)
- [ ] Wanneer huidige sectie -> deze ook toevoegen of voorgaande waarde overschrijven
- [ ] Het resultaat als array sturen naar het kpi endpoint
- [ ] bovenstaande moet altijd gebeuren
- [ ] nieuw veld target value in storyline context toevoegen
- [ ] verborgen elementen in de huidge sectie kunnen target values van voorgaande secties overschrijven

**Comment by mattijsstam** [comment]
- [ ] moet altijd gebeuren
- [ ] nieuw veld target value in storyline context, deze wordt meegestuurd uit ander secties
- [ ] opsturen alle interactieve elementen tot nu toe
- [ ] schaduw elementen kunnen target values overschrijven
