### ISSUE TITLE
MD rendering of links and line endings

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#58]
No biggy, just noticed this rendering behavior if hyperlinks span multiple rules in `md` :
![image](https://user-images.githubusercontent.com/78690362/180172505-a057c2ea-6056-42a3-a555-56f0eb3dbaf1.png)

While local markdown preview produces:
![image](https://user-images.githubusercontent.com/78690362/180172764-e8eef5a3-9bda-49eb-9767-5ac5c6d28def.png)

**Comment by Erikvv** [comment]
Niet meer relevant.
