### ISSUE TITLE
Interactive element 'single select' doesn't accept my input, returns white screen

### ISSUE THREAD

**Issue by GillisHommen** [ZEnMo/Holon-webapp#581]
**Describe the bug**
White screen when saving changes in option 2 of 'single-select' interactive element. Changes are not saved.

**To Reproduce**
1. Go to [(https://holon-v2-acceptatie.azurewebsites.net/wt/cms/snippets/holon/interactiveelement/edit/7/)]
2. Option 1 is uitgewerkt/ingevuld
3. Vul nu bij optie 2 de volgende velden in:
![image](https://user-images.githubusercontent.com/98752265/229811439-086e3171-6e7f-4b9b-a377-0548ff6124be.png)

5. En druk op 'save'
6. See error (wit scherm, en aanpassingen zijn niet opgeslagen)

**Expected behavior**
Aanpassingen worden wel opgeslagen, en ik kan verder gaan met het instellen van het interactive element.

**Actual behavior**
Zie "To Reproduce"

**Additional context**

**Comment by Erikvv** [comment]
Ik doe een poging dit deel van het systeem te begrijpen.

**Comment by Erikvv** [comment]
Als ik dit lokaal probeer te reproduceren krijg ik deze validatie error 

![Screenshot from 2023-04-05 10-13-48](https://user-images.githubusercontent.com/1748197/230022201-c48ae5c9-9fc2-462f-9ed5-75ceeda31bfc.png)

**Comment by TAVMWB** [comment]
Ik heb het lokaal gereproduceerd op een lege database, het lijkt er op alsof er incorrecte velden staan in de dropdown van Model attribute aan de voorkant. De dropdown bevat velden van de rule's model (sub)type, terwijl je hier de velden zou willen van het model wat geselecteerd in in de optie Relation field.
![image](https://user-images.githubusercontent.com/105435881/230395889-55594feb-ee0d-4b48-bbb4-4d3537509bdc.png)

@mattijsstam kan jij dit rechttrekken in de Jquery?

**Comment by mattijsstam** [comment]
@TAVMWB ik ga het fixen

**Comment by mattijsstam** [comment]
@TAVMWB  merge request staat klaar
