### ISSUE TITLE
Max to number of pages in wiki menu

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Holon-webapp#582]
**Describe the bug**
When I add new pages to the wiki they only appear in the wiki menu when I delete others. It seems the menu has a maximum amount of pages to be visible. Also not all subpages have to be folded open when entering the wiki.

**To Reproduce**
Add new page to the wiki and check if it appears in menu

**Expected behavior**
I expect all pages to appear in the menu. Starting with just the direct wiki child pages and when folding open the subsequent child pages of main pages appear in the menu.

**Actual behavior**
The menu shows all pages and just the first 17 created.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/38351577/230023959-5c5b6d9a-026a-4002-ade4-c0eb9dafc7ed.png)

**Additional context**

**Add labels**
- [x] Correct label for origin (e.g. `bug` of `feature enhancement` of `nice to have`)
- [x] Correcte label voor categorie (e.g. `interactive element configuratie`)

**Comment by pascalalferink** [comment]
I notice the following:
The menu on the wiki reflects the items form the api call.   (https://holontool.nl/wt/api/nextjs/v1/page_relative_urls/?type=main.WikiPage)
It seems to me, that nog all wiki-items are passed through to the frontend.

Together with @broekhuisg I found out that Django has a default limit of 20 items per page via the setting WAGTAILAPI_LIMIT_MAX.  We have changed this value to 1000. 


![Image](https://user-images.githubusercontent.com/13336728/231156971-ac9e3bcb-675e-41c8-9d9c-a70a7ba25a01.png)
