### ISSUE TITLE
Dropdown of model subtype does not work in CMS

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#590]
When adding interactive elements the model subtype is needed to filter the correct assets. The dropdown does not work atm. The former workaround (saving the element and reopening it) does not work either. 

![Image](https://user-images.githubusercontent.com/97597063/230611934-bdb6da24-daff-4139-b6f0-87a075c82834.png)

**Comment by TAVMWB** [comment]
linked to #591

**Comment by thesethtruth** [comment]
Closed because fixed in #591
