### ISSUE TITLE
Check box in subfilter on CMS is not working

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#591]
The checkbos is required to make sure the value of the interactive element is used. Clicking does not give any feedback/reaction.

![Image](https://user-images.githubusercontent.com/97597063/230612348-2e05a326-707c-4935-9ae6-a9e656fe3fca.png)

**Comment by thesethtruth** [comment]
@mattijsstam kan jij deze oppakken. Ik weet niet waarom de CORS wel werkt op productie maar hier niet. We gebruiken als het goed is hetzelfde entrypoint tenzij dat anders is via de Azure pipeline dan ik nu begrijp. 

Dit gaat ook mis voor het ophalen van de `jquery` spagheti 🤌

**Comment by mattijsstam** [comment]
Ah dit is iets in de CORS instellingen van Azure storage, ik heb https://pizzaoven.holontool.nl toegevoegd dus nu zou het weer moeten werken. Misschien wel even chache weggooien als je toch nog foutmeldingen krijgt

**Comment by thesethtruth** [comment]
@petertue ik heb de boel opnieuw gestart. Werkt dat nu inderdaad?
