### ISSUE TITLE
inverted filters & randomizers are missing in the pizza oven

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#592]
Inverted filter and randomizer (of selected models) features are not on the pizzaoven. However, they are already tested on main (according to Matthias)

**Comment by TAVMWB** [comment]
randomizer was missing a panel, legit bug. Added in branch 592. Inverted filter was fixed by updating pizzaoven to main branch changes

**Comment by thesethtruth** [comment]
Fixed, working on the devops did not include the latest version of the main branch.
