### ISSUE TITLE
Cannot select assets to add. CMS --> interactive elementes --> 'add child models'

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#594]
In the pizzaoven CMS, asset models cannot be selected at 'add child model' with interactive elements. The dropdown remains empty.

Potential reason: templates were not transferred to the pizzaoven, but probably something else goes wrong as the templates are part of the fixture. 

![Image](https://user-images.githubusercontent.com/97597063/230964713-2fd88111-9adc-4a81-ae74-a259195b3a96.png)

**Comment by TAVMWB** [comment]
@PeterHogeveen wat zegt je browser console bij het laden van een pagina? Wanneer je op F12 drukt in de browser en kijkt in het tabje "console"

**Comment by petertue** [comment]
Zie plaatje voor wat de console print. De fixture waarmee ik mee werk zou ik zelf niet weten. Die is ingeladen door webdev team.

![image](https://user-images.githubusercontent.com/97597063/231111097-962639ec-e9e7-4d7c-b71f-557d52828afd.png)

**Comment by TAVMWB** [comment]
Als je de pagina herlaad terwijl je de console open hebt, krijg je dan meer te zien? Of het zelfde?

**Comment by petertue** [comment]
Ja zelfde message. Ik zie nu in de Django database nu (waar ik eerste niet bij kon) dat er inderdaad helemaal geen templates zijn meegekomen in deze omgeving.

Als ik daar eentje aanmaak dan krijg ik hem ook in het CMS te zien. Dus het werkt in zekere zin. Het betekent wel dat we voor het testen alle templates opnieuw moeten aanmaken. Hopelijk is dat dan eenmalig.
