### ISSUE TITLE
Peteren Jorrit hebben geen toegang tot de Django database met zijn inlog + wachtwoord

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#599]
Ik gebruikte vorige week Gillis zijn gegevns om bij Django te komen, want zelf heb ik daar geen toegang tot. Dat was in principe prima, maar nu merk ik dat ik dan ook in het CMS van account switch. En momenteel meotne we tegelijkertijd dingen doen, weet niet of dat houdbaar is.

edit: Jorrit heeft zelfde issue

**Comment by petertue** [comment]
Die van de pizza oven: https://pizzaoven.holontool.nl/wt/admin/login/?next=/wt/admin/

Alleen Gillis heeft toegang tot die omgeving met hetzelfde wachtwoord en gebruikersnaam als hij voor de pizzaoven CMS gebruikt.

**Comment by mattijsstam** [comment]
@petertue er stond nog een vinkje uit bij jouw naam, zou je het nog een keer kunnen testen?

**Comment by mattijsstam** [comment]
Ook voor @JorritvandenHouten zou het nu moeten werken

**Comment by petertue** [comment]
Ja het werkt!

**Comment by petertue** [comment]
Dit issue is weer teruggekomen. Kan dat zijn door de update van de pizza oven?

**Comment by mattijsstam** [comment]
Ja, er wordt een backup teruggezet en daar zit dit inderdaad nog in. @thesethtruth wil je de backup aanpassen of even een actie toevoegen aan de update om Jorrit en Peter "staff status" te geven?

**Comment by thesethtruth** [comment]
Doe ik!
