### ISSUE TITLE
Users can view HOLON scenario's

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#6]
### Description

The core of the application is the functionality of letting the user "play" with the HOLON model via predefined scenario's. In order to do this the user has a simple interface with some sliders and resulting graphs to view results of the HOLON model.

![image](https://user-images.githubusercontent.com/32770108/176614907-72798ef6-afa5-4931-9994-930df669e518.png)

This issue is about creating the sliders and the overal setup of the block, in #5 the actual editing and updating of the holon model is developed.

### To discuss

- Which buttons, graphics and texts of this block are dynamic or static? Sliders, select, radio
- Which options are presented in the "Juridisch" list? To be delivered
- Which text is behind the (i) on the circles and how is this text presented? Popover text

### Acceptance criteria

- [ ] Developers can configure a single HOLON scenario block for several scenario's
- [ ] Developers can disable inputs for fixed components
- [ ] Users get visual feedback of the numbers based on a scale
- [ ] Users can toggle between local or national level
- [ ] Users can change input elements if not disabled
- [ ] Users can view the texts and graphs of the scenario
- [ ] Users can view more information about the results

**Comment by pascalalferink** [comment]
Basics of component  <Scenarios /> have been made:

- when 'locked' is added as property (<Scenarios locked />), the inputs are disabled (see screenshot 3)
- when updating one of the inputs, the right side gets an overlay (see screenshot 2) with a calculate button
- Right now, the values in the orange circles are random number, an api-call should be made.

![image](https://user-images.githubusercontent.com/13336728/176922039-9045d091-35a7-4d7d-b83e-cb9beeffe790.png)
![image](https://user-images.githubusercontent.com/13336728/176922362-f4586237-1432-4315-9510-44f8a5e6da6f.png)
![image](https://user-images.githubusercontent.com/13336728/176922683-1ba22c47-a406-4d3c-9a0a-ca6d276db7a0.png)

**Comment by pascalalferink** [comment]
Design has been updated, so is the code:
![image](https://user-images.githubusercontent.com/13336728/177563895-67516cd1-d5e7-40a4-a04c-8313b5070cff.png)
