### ISSUE TITLE
Wrong options in model-attribute dropdown for relational attribute filters in interactive elements

### ISSUE THREAD

**Issue by GillisHommen** [ZEnMo/Holon-webapp#601]
**Describe the bug**
Wrong options in dropdown for relational attribute filters in interactive elements (all types)

**To Reproduce**
1. Go to https://pizzaoven.holontool.nl/wt/cms/snippets/holon/interactiveelement/edit/3/
3. Scroll down to rules 1, relational attribute filter 1. 
4. Dropdown 'model attribute' lists attributes of energy asset instead of attributes of grid connection object. 
![image](https://user-images.githubusercontent.com/98752265/231147149-89e253a7-b03b-415a-9400-d861e0088f4a.png)

6. Also, when trying out the slider on https://pizzaoven.holontool.nl/casus-overzicht/bedrijventerrein-energy-hub/bedrijventerrein-energy-hub-uitdaging/ and using 'inspect', the response is: 
error_msg | "something went wrong: target count (6) for a single model type cannot be larger than the total amount of filtered objects (0)"

**Expected behavior**
Dropdown 'model attribute' in relational attribute filter should show attributes of the model in 'relation field', instead of the attributes of the model type selected at the 'rule' level.

**Actual behavior**
Wrong options in model-attribute dropdown for relational attribute filters in interactive element

**Screenshots**

**Comment by GillisHommen** [comment]
Ik heb nu bij dit interactive element een vergelijkbare fout:
https://pizzaoven.holontool.nl/wt/cms/snippets/holon/interactiveelement/edit/11/

De dropdown 'model attribute' bij het relational attribute filter van option 2 geeft de verkeerde lijst weer. Echter, dit is pas het geval nadat ik andere rules/filters aan het interactive element toevoeg, in eerste instantie kreeg ik WEL de goede lijst bij deze dropdown.

**Comment by mattijsstam** [comment]
@GillisHommen ik heb even naar de issue gekeken en het originele issue kon ik op de pizzaoven niet reproduceren. Als ik naar https://pizzaoven.holontool.nl/wt/cms/snippets/holon/interactiveelement/edit/11/ ga en daar een nieuwe relation filter toevoeg met jouw instellingen krijg ik het volgende:

![image](https://user-images.githubusercontent.com/32770108/231980773-5b17044e-5d0a-4ea0-b8ca-f60f14822f19.png)

Ik heb dit namelijk in een eerdere issue opgelost #581 maar het kan zijn dat dit nog niet online stond toen jij het testte. Ook jouw tweede fout lijkt opgelost te zijn maar bij deze ook de vraag om dit nog even in jouw omgeving te testen.

Wat betreft punt 4, graag hier een losse issue van maken en aan Sem of Matthias toewijzen

**Comment by TAVMWB** [comment]
@GillisHommen wanneer je een losse issue van punt 4 hebt gemaakt kan je deze op mijn naam zetten, dan kunnen we daar verder naar kijken. Het zou fijn zijn als je in die issue ook kan doorgeven hoe je je filters en je rules hebt geconfigureerd.

**Comment by TAVMWB** [comment]
@GillisHommen @mattijsstam kan ik deze issue sluiten?

**Comment by GillisHommen** [comment]
Ik denk dat het issue van punt 4 kwam omdat ik wilde filteren op één specifiek ID, wat echter door het clonen niet gevonden wordt, omdat de IDs daarbij niet behouden blijven.

**Comment by TAVMWB** [comment]
Fout heb ik lokaal gereproduceerd. Handelingen:
- voor een rule met model type Contract, subtype DeliveryContract
- Maak een nieuw relation attribute filter aan, selecteer hier "Actor|actor", en model attribute op group. Model attribute laat op dit moment de correcte lijst zien.
![image](https://user-images.githubusercontent.com/105435881/232707254-b11d9139-305b-4619-8651-7368f9cedf80.png)

- save gaat goed
- Bij het opnieuw openen van de interactive element is het veld model attribute leeg, de lijst van model attribute is een lijst van contract attributes (ipv actor attributes) en wanneer er gesaved wordt krijg je een foutmelding.
- De relation field togglen naar "Actor|contractScope" en weer terug zorgt dat de model attributes lijst weer klopt, maar deze kan dan nog niet gesaved worden
![image](https://user-images.githubusercontent.com/105435881/232709277-1d9e31ff-14f3-4722-90f6-0a0823069658.png)

**Comment by TAVMWB** [comment]
Opmerking: het veld "group" is een foreign key dus dit moet worden aangegeven met een id, niet een string.

**Comment by TAVMWB** [comment]
@mattijsstam weet jii misschien waarom bij het tweede keer laden van de pagina de lijst nog niet klopt? Of is dit misschien al in een andere issue opgelost?

**Comment by mattijsstam** [comment]
deze wordt opgelost in #596
