### ISSUE TITLE
Casus buurtelektrificatie op pizzaoven geeft internal server error

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#603]
ALs ik op pizzaoven.holontool.nl navigeer naar de verhaallijn van de casus buurt elektrificatie krijg ik direct een internal server error. 

Klik op 'verhaallijn buurtelektrificatie' via deze link: https://pizzaoven.holontool.nl/casus-overzicht/buurtelektrificatie/.

![Image](https://user-images.githubusercontent.com/97597063/231160485-49cb16e7-2ff4-4a7d-8125-7a1746d7fd11.png)

**Comment by mattijsstam** [comment]
@petertue volgens mij is dit opgelost, zo ja kun jij de issue sluiten?

**Comment by petertue** [comment]
Ja!
