### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by MariaBee3** [ZEnMo/Holon-webapp#61]
The site currently has some responsiveness issues. I've added the first things I found here, please add anything else you find. 
- [x] sides of video page disappear; 
- [x] cookiebar becomes to wide for screen (resulting in a horizontal scrollbar)
- [x] illustrations next to text become very small
- [x] textblocks - font too big
- [x] outlining 'resultaten - indicatoren' rounds
- [x] outlining forms fields
- [x] blocks are higher than the viewport, so the scrolling won't work correct anymore
- [x] sides of contact form dissapear

**Comment by Jay3162** [comment]
Hiya, I can handle this for you if you like.

**Comment by MariaBee3** [comment]
@Jay3162 Hai Jamal, thanks for the offer. We haven't developed a policy yet on open source collaboration, so for now we will take this up ourselves. Shall we get back to you once we have developed our policy on this?

**Comment by Jay3162** [comment]
> @Jay3162 Hai Jamal, thanks for the offer. We haven't developed a policy yet on open source collaboration, so for now we will take this up ourselves. Shall we get back to you once we have developed our policy on this? 

Sure that's fine, and I hope everything goes well with this one.
