### ISSUE TITLE
Feedbackmodals and Holarchy feedback image won't work with multiselect

### ISSUE THREAD

**Issue by pascalalferink** [ZEnMo/Holon-webapp#632]
In the application are feedbackmodals and holarchy feedback images.

The visibility of these two items can be determined in the CMS by adding conditions.
The current conditions are  

1. greater then,  
2. greater or equals then, 
3. equals, 
4. not equals, 
5. equal or smaller then.  
6. smaller then,

These conditions work fine for assessing single select items, but the user can also add multiselect items. Currently it is nog possible to assess theses items.

an example:
A user has added the following multiselect
_"On what days do you go to the office? "_

- Monday,
- Tuesday
- Wednesday,
- Thursday
- Friday

If the user want to show a feedbackmodal when "Monday" and "Friday" are selected, There is currently no way of assessing this.

At least one thing should be done:

- [ ] if people are assessing a multiselect, the page should not crash
- [ ] Optional: Make it work with multiselect, with a new userstory

**Comment by thesethtruth** [comment]
Helder. Bedankt voor de goede uitwerking. 

Ik heb het overlegd met de modeleurs en zij voorzien voor de komende 3 casussen **geen multiselects.** Dus inderdaad:
- [ ] ervoor zorgen dat de pagina niet crasht en;
- [ ] het liefste ook toevoegen aan de hulptekst dat dit niet mogelijk is en;
- [ ] een userstory maken die deze functionaliteit beschrijft (heel basaal) zodat het wel transparant terug te vinden is dat we dit niet geimplementeerd hebben en het op de backlog staat.

**Comment by pascalalferink** [comment]
@thesethtruth , 
issue #635  covers all three actions from your list above. If you agree, can you close this issue?

**Comment by thesethtruth** [comment]
Yes, perfect!
