### ISSUE TITLE
Cloned scenarios are not deleted properly

### ISSUE THREAD

**Issue by TAVMWB** [ZEnMo/Holon-webapp#654]
Interactive elements modify the data in a scenario. In order to make sure the original scenario remains untouched, the scenario is deep-cloned and the clone is modified. 

After the endpoint returns a result, this cloned scenario is no longer needed and should be deleted. To prevent the deletion from blocking the endpoint result until completion, we previously implemented an async approach using standard Python threading to delete the scenarios (in `holon/models/scenario.py`, `delete_async()`).
This works locally, however does not work properly when deployed on the pizzaoven or another environment. 

We suspect this might has to do with the servers not having access to multiple workers, and/or Django not allowing multiple threads.

Cloned scenarios can be manually deleted, but if this is done infrequently it significantly affects CMS/interactive element performance. Thus it would be very helpful if the automated approach would work

**Comment by TAVMWB** [comment]
@Erikvv Heb jij misschien tijd/zin om hier naar te kijken?

**Comment by mattijsstam** [comment]
https://pypi.org/project/django-crontab/

**Comment by Erikvv** [comment]
> https://pypi.org/project/django-crontab/

Zoals ik het lees moet je daar dus cron voor installeren in de container.

Het lijkt me gemakkelijker om een 2e python container te starten met dezelfde image, met als commando een bash loopje.

**Comment by thesethtruth** [comment]
closed as new implementation does no longer depend on copies (notify @Erikvv @TAVMWB)
