### ISSUE TITLE
Sommige geldstromen worden verkeerde kant op berekend.

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#673]
Ik heb gas, elektriciteits en diesel contracten met hun respectievelijke leveranciers (zijn allemaal groups van actor type supplier energy). Alle contracten zijn op dezelfde wijze op gezet. Maar op de een of andere manier betalen leveranciers gas en diesel aan de huishoudens: 

![Image](https://user-images.githubusercontent.com/97597063/234595023-be01e99f-0379-4680-90ff-8fe3093a3b67.png)

Via deze link kom je bijde bron van dit plaatje: https://holontool.nl/casus-overzicht/buurtelektrificatie/test-challenge/

Een quick fix is om die prijzen negatief te maken. Maaar misschien is het handig om uit te vogelen waar het precies mis gaat. De contracten in de Django database staan de goede kant op gedefinieerd:

![Image](https://user-images.githubusercontent.com/97597063/234595319-d1d2909e-3113-4aa0-b5bc-809ff8bbe23c.png)

Goed om te weten dat zowel de gas als dieselcontracten via een template en interactief element worden toegevoegd. Dus niet standaard in de fixture. Misschien dat dat ergens mee te maken heeft?

**Comment by thesethtruth** [comment]
Vraag aan @petertue of deze ook gesloten wordt als de oplossing van @GillisHommen in #679 doorgevoerd wordt.

**Comment by thesethtruth** [comment]
Closed as issue was in AnyLogic and is now fixed
