### ISSUE TITLE
Fix on `kostenbaten` calculations

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#679]
- [ ] Sign of `EnergyTransactionVolume_kWh` will be flipped in AnyLogic @GillisHommen and as a result the following logic should also flip:
```python
        volume = obj.get("EnergyTransactionVolume_kWh", 0.0)
        if volume < 0:
            return volume * (
                obj.get("feedinTax_eurpkWh", 0.0) + obj.get("feedinPrice_eurpkWh", 0.0)
            )
        return volume * (
            obj.get("deliveryTax_eurpkWh", 0.0) + obj.get("deliveryPrice_eurpkWh", 0.0)
        )
```
- [ ] Add a proportional tax method that depends on financial volume of other contracts  
e.g. tax on energy delivery bill. 
    Two options:
    1. AnyLogic takes care of determining these taxes and all `financialTransaction` volumes
    2. Cost module also determines the taxes based on other contracts of a single agent (starter in [update-kosten](https://github.com/ZEnMo/Holon-webapp/tree/update-kosten))

**Comment by GillisHommen** [comment]
Sign of EnergyTransactionVolume_kWh has been flipped in AnyLogic. A positive energy transation volume now indicates an energy flow from contractHolder to contractScope. Or vice versa, a new energy use by the contract holder corresponds to a negative energy transaction volume. 

This is now in line with the financial transaction volume, where also a negative financial transaction volume indicates money flowing from contractHolder to contractScope.

**Comment by GillisHommen** [comment]
I have implemented accounting of money-flows corresponding to all energy carriers, including taxation (proportionalTax_pct) in Anylogic in the Base_1may model. This results in the contractData output giving 0 for all energyVolumes and non-zero for financialTransactionVolumes. This also applies the delivery/feedin tax with the correct sign.

It is possible to disable/roll-back this functionality by setting the anylogic model input "B anylogic costs for all contracts" to false.
