### ISSUE TITLE
Holontool.nl/inbreng does not seem to work

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#68]
https://holontool.nl/inbreng
![image](https://user-images.githubusercontent.com/78690362/180974241-493c7c6d-6232-4629-8ccd-e430df16a75b.png)

https://github.com/ZEnMo/Holon-webapp/blob/1e1d11f70fae9f0488415f005bebfe67b2c6562e/frontend/next.config.js#L15-L21

**Comment by MariaBee3** [comment]
@thesethtruth heb je dit al geprobeerd in een andere browser? Het kan zijn dat de route is opgeslagen in je cache (dat is wat permanent: true doet). Als het goed is werkt het wel in een andere browser.
