### ISSUE TITLE
Add a priority/order field to holarchy images

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#689]
Current behaviour requires managers to make exclusive condtionals, which can become cumbersome. 

Instead, we could add a priority/order field that allows CMS'ers to 'stack' images where higher/lower level images are sorted based on the priority/order field. With that functionality, the content manager can have more flexible/less tedious conditionals.

**Comment by mattijsstam** [comment]
- [ ] Check if order in which images are configured is used when handling conditions.
- [ ] Add documentation to wiki.

**Comment by broekhuisg** [comment]
Ik heb het getest, ook aan de hand van de geleverde tabel.
Naar mijn inziens werkt deze functionaliteit naar behoren. De images worden op basis van de order waarin de images staan geplaatst in het CMS getoond, inclusief de condities die worden neergezet.

**Comment by thesethtruth** [comment]
Top! Bedankt voor het onderzoek @broekhuisg!
