### ISSUE TITLE
Users can register for updates on the HOLON development

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#7]
### Description

The final slide of the one page website shows a registration form where the user can fill in their name, email and company name to receive updates.

![image](https://user-images.githubusercontent.com/32770108/176615337-c9effa7f-2e0e-46c2-aa49-d7a4c9749c06.png)

### To discuss

- Which fields are required? Bedrijf is optional
- What should happen if a users clicks the "Bevestig" button? store in database
- What is the functionality of the emoticons? -> users can click on the emoticons -> click get stored in the backend -> 1 click per browser session (nice to have)

### Acceptance criteria

- [ ] Users can register themselves for updates on the HOLON tool
- [ ] Users receive feedback about required fields
- [ ] Users can press an emoticon to quickly add feedback, after refresh button becomes selectable again
- [ ] Users receive feedback after submitting the form, button changes to submitted V

**Comment by antw** [comment]
@broekhuisg Would you mind if I took the frontend part of this, and you took the backend? I've not used Django before so I imagine you'll be able to sort out the backend and API faster than I.

**Comment by broekhuisg** [comment]
@antw Yeah of course. No problem!

**Comment by broekhuisg** [comment]
@antw @mattijsstam I finished the backend (created a pull request for Mattijs) and pushed it in branch 7-users-can-register-for-updates-on-the-holon-development.  There I created an endpoint /update-registrations where you can POST new `update registration` form data.

**Comment by antw** [comment]
Excellent, thanks! I have the form nearly ready to go. I'll get it hooked up today.
