### ISSUE TITLE
Website becomes unresponsive when using TVW holarchie-view

### ISSUE THREAD

**Issue by GillisHommen** [ZEnMo/Holon-webapp#700]
**Describe the bug**
Fleur is using the holarchie-view of the TVW case to test the activation of various holarchie-images. To do so, she sets the dropdowns of the 6 neighbourhoods to various combinations. However, every time you change a dropdown, a new simulation is triggered, which especially for the TVW-case is a big load on the backend. We suspect that when multiple TVW-runs are triggered by changing consecutive dropdowns, the website becomes completely unresponsive, also for other users.

**To Reproduce**
1. Go to '...' https://holontool.nl/casus-overzicht/transitievisie-warmte-gemeente/transitievisie-warmte-gemeente-uitdaging/
2. Click on holarchie-tab
3. Change the heating systems for all neighbourhoods
4. See the website become unresponsive.
5. While waiting, try opening holontool.nl in a different browser-tab, and notice how even just opening the front-page is now very slow. (to the point it gives a timeout)

**Expected behavior**
Either the website should be able to handle all the requests when setting multiple dropdowns, of the requests should only be made after clicking some 'GO!'-type button.

**Comment by thesethtruth** [comment]
@GillisHommen kan dit gesloten worden?

**Comment by GillisHommen** [comment]
Ik heb hier niets meer over gehoord, denk dat het inmiddels geen issue meer is. Geloof dat ik het toen het ingeschoten voor @JorritvandenHouten en fleur die er toen tegenaan liepen.

**Comment by thesethtruth** [comment]
Thanks! Ik sluit het!
