### ISSUE TITLE
Doorrekenen casus doet te veel queries

### ISSUE THREAD

**Issue by Erikvv** [ZEnMo/Holon-webapp#703]
Samen met Jorrit bij de casus Transitievisie warmte geconstateerd dat deze onredelijk veel queries afvuurt (~100K), zelfs als er 0 interactieve elementen zijn ingesteld.

Dit leidt tot 

- lange responsetijd of timeout voor het berekenen van de casus
- tijdelijke outage van de website
- ontbreken van Sentry logging door te veel spans (limiet is al opgehoogd van 1k naar 20k)

Dit is waarschijnlijk een zgn N+1 queries probleem door ongeoptimaliseerd gebruik van het ORM.

**Comment by SCHS13** [comment]
Als ik het lees en naar de code kijk, moet ik aan de volgende dingen denken. Op dit moment zijn het aannames
- Als er met 0 interactieve element al problemen zijn, ligt dit probleem in eerste instantie niet bij de uitvoering van regels of filters
- Andere operaties die veel in de db doen, zijn het klonen en verwijderen van een scenario
- Klonen
   - Er wordt al veel geprefetcht om het N+1 query probleem te voorkomen, maar niet niet overal 
   - Elk model dat gekloond wordt is een aparte query, omdat batch_create op een polymorhpicqueryset niet werkt -> veel queries
 - Verwijderen
    - Modellen moeten individueel verwijderd worden, omdat een polymorphicqueryset niet in een keer verwijderd kan worden -> veel queries

Dus als de aannames correct zijn, kan er naar het gebruik van prefetchen in de kloon functie nog gekeken worden. Hoe querysets beter verwijderd en gecreate kunnen worden, weet ik nog niet

**Comment by thesethtruth** [comment]
Is dit issue te sluiten?
