### ISSUE TITLE
Default value in snippet interferes with target values in first section of page. 

### ISSUE THREAD

**Issue by MariaBee3** [ZEnMo/Holon-webapp#706]
**Describe the bug**
If an invisible interactive element with a target value is added in a section of a page, this should not be send along with the API call of that section (it should be added to all underlying sections). However, if this element has been given a default value within the snippet, it will be send along with this default value in the api call of that section. 

**To Reproduce**
1. Add an interactive input element snippet with a default value in Wagtail. 
2. Add this interactive element to a section on a storyline or challenge page. Deselect 'visible' and give the element a target value. 
3. Open the page in the front-end.
4. See in the API call made in that section that the element is added with the default value from the snippet. 

**Expected behavior**
This element should not be added to the section. It should be added to the underlying sections with the target value. 

**Actual behavior**
This element is added to the section, with the default value from the snippet. In the underlying sections it is added with the target value as expected.

**Comment by MariaBee3** [comment]
@GillisHommen Ik vond deze bug terwijl ik werkte aan #701  Kan jij inschatten hoe vaak er een default value in de snippets wordt meegegeven en in hoeverre dit een probleem vormt?

**Comment by GillisHommen** [comment]
@MariaBee3, hoe is dit issue nu aangepakt? 
Ik begreep dat de default-value van een snippet nu op inzichtbaar wordt gezet (maar niet verwijderd?), wanneer je de snippet aanmaakt. Betekent dit dat bestaande snippets die al een default value hebben, deze wel behouden? 

Dit issue zegt bij 'expected behavior' dat de default value van de snippet zelf niet meegestuurd wordt, indien het een 'invisible' snippet is met een target value. Zijn er situaties dat die default value wel nog een rol speelt?

**Comment by MariaBee3** [comment]
@GillisHommen Ow ja, ik had het nog niet hier gedocumenteerd. We hebben het in issue #702 meegenomen. 
De aanpak voor dit issue was inderdaad om de default-value in de snippet op onzichtbaar te zetten. Op basis van jullie ervaringen verwachten dat deze weinig tot nooit is ingevuld, maar zo weten we iig dat er geen hele rare dingen gebeuren als dat wel zo is. 

De default waarde in de snippet speelt een rol als een element geen default of target value op de pagina meekrijgt. Dan wordt de default waarde vanuit de snippet gepakt. Als deze er ook niet is dan wordt bij zichtbare elementen de eerste optie of 0 als default waarde genomen. Bij ontzichtbare elementen is er dan gewoon geen waarde.
