### ISSUE TITLE
Wiki menu doesn't show all pages

### ISSUE THREAD

**Issue by naudloomans** [ZEnMo/Holon-webapp#718]
The wiki menu does not show all pages. Instead it shows the 20 first created pages.

To reproduce see difference in pages on holontool.nl.wiki and in wiki CMS

We would like to see all main pages visible in the initial menu with fold out to be opened by the user.

![afbeelding](https://github.com/ZEnMo/Holon-webapp/assets/38351577/fdd51579-1fde-4596-9cea-cc0b99717c9c)

![afbeelding](https://github.com/ZEnMo/Holon-webapp/assets/38351577/f969dbe0-722a-41e8-bc51-17ca924b84a4)

**Comment by pascalalferink** [comment]
We have encounterd this issue before: see in https://github.com/ZEnMo/Holon-webapp/issues/582

When I look at the commit, I see WAGTAILAPI_LIMIT_MAX was added. It seems this didn't solve the issue.

@broekhuisg could we look at this when you are back?
