### ISSUE TITLE
Add new gridconnections and actors with contracts and energie assets

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#725]
In de Sandbox van de buurtelektrificatie kunnen gebruikers zelf instellen hoeveel huizen er zijn per huis type. Dat betekent dat er nieuwe gridconnections (huizen in dit geval) toegevoegd moeten kunnen worden vanuit het CMS. De nieuwe gridconnections moeten dan ook direct gekoppeld worden aan nieuwe toegevoegde actoren. 

Idealiter staan binnen de nieuwe gridconnection al de standaard energie assets, en staan binnen de nieuwe actor al de standaard contracten. Dat zou ik bijv via django database al kunnen aangeven(?). Hoewel die assets en contracten handmatig toegevoegd kunnen worden, lijkt me dat minder optimaal voor performance.

Het moet ook mogelijk zijn om gridconnections + hun bijbehorende actors te verwijderen (incl contracten en energieassets).

**Comment by SCHS13** [comment]
@petertue Ik heb nog een aantal vragen/ wilde een aantal zeker weten:

- Moeten gridconnections met ruleactionadd ook aan scenario's als parent kunnen worden toegevoegd? (Op dit moment kan het alleen aan actors)
   - Misschien is het handiger om de nieuwe gridconnections met de template actor mee te laten komen. Dat scheelt werk om regels en actions in te stellen. Of had je het zo voor ogen :) Of alle twee de mogelijkheden
- Contracten die meekomen, omdat een actor wordt toegevoegd, kunnen een scope hebben? Die scope kan ook al in het scenario zelf zitten?
- Voor het verwijderen: gaat het op dit moment ergens nog niet goed? 
    - Als gridconnections met bijhorende actors verwijderd moeten worden, is het al een oplossing om dit in twee regels te doen? Zo blijft alles generiek en is de situatie dat alleen gridconnections verwijderd moeten worden nog intact.
