### ISSUE TITLE
Gebruikers kunnen niet de juiste informatie inzien bij het klikken van de I op de KPI's

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#727]
Observaties:
- [ ] Het is nu een link in een knop zonder extra informatie (dan is een directe link misschien beter)
- [ ] Bij het scrollen van de sectie valt de informatie in deze pop up onder de balk van holarchie/verhaallijn:
![Image](https://user-images.githubusercontent.com/78690362/242591545-b401b7bc-7448-49c7-8158-087be78dc8d6.png)

Gewenst:
- [ ] Korte informatie per KPI in de popup (zoals in het oorspronkelijke ontwerp) met een link naar de wiki pagina
- [ ] Zichtbaar ook als de volgende sectie eronder is (bijv pop omhoog)

**Comment by pascalalferink** [comment]
De popup was er al, heb de positie aangepast

![Image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/5c941c30-1302-48b1-a040-0dac55746234)
