### ISSUE TITLE
Bug: alle termen zijn directe links naar de wiki geworden zonder de modal ertussen

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#728]
Voorheen was er een modal tussen de term en de wiki die een korte uitleg gaf. Daarbij kon je op een knop drukken om naar de wiki te gaan. Nu wordt de gebruiker direct gelinkt naar de wiki zonder dat die daarvoor kan kiezen. Dat breekt de ervaring van de interactievorm.

**Comment by thesethtruth** [comment]
@pascalalferink  @naudloomans @Erikvv Weten jullie hier misschien meer van? Mij staat niet bij dat we hier bewust voor gekozen hebben,

**Comment by pascalalferink** [comment]
I tested it and it still works:

- In a text area, you select text (screenshot 1)
- in the popup, you click the quotes-button  (screenshot 1)
- Another popup opens in which you can choose a wiki-page  (screenshot 2)


![Image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/57f88521-7413-42d3-a423-0cd10dc822f5)




![Image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/a5119876-fbb1-4401-9ba8-504ad1e4b0f0)




![Image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/16acba74-3ca5-4c1a-9cff-16353df445e9)
