### ISSUE TITLE
Research standard wiki/static page technologies for next.js

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#76]

**Comment by antw** [comment]
**Initial requirements** are:

- Provide files containing documentation
- Render the content as HTML, including tables, quotes, code, and images
- A listing of the available pages which can be displayed in a sidebar

**Longer-term**, features of a Wiki might include:

- The ability to edit content through the browser
- The ability to add new pages, or delete existing pages

Maybe I'm getting tripped up on the "wiki" term, but it seems obvious that the ability to _edit_ pages through the browser isn't compatible with doing this entirely in Next.js. We'd need _some_ kind of backend to manage the content. If we were to manage the content through the Django app – perhaps having it serve the markdown and other relevant metadata as JSON – it can take care of the CRUD operations and create a list of the available pages for a sidebar, while Next will render it as HTML.

**For now**, I will assume that we are only concerned with creating static documentation pages, and that it is not necessary to edit the pages through the browser, I think we have a couple of options.

## Next.js pages

Next.js already has support for generating static pages, and it is easy enough for us to add a directory containing documentation files in Markdown format and render those in the browser. It may be possible for us to pre-render these pages using [`getStaticProps`](https://nextjs.org/docs/basic-features/data-fetching/get-static-props), but I haven't tried this yet.

There's no built-in way for us to create a listing of available pages. We'd need to either define the sidebar ourselves – either as  React component or using JSON – or find a way to do this using a custom Next.js plugin or by taking inspiration from [tailwind-nextjs-starter-blog](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/de43792edb2e9ed13552c3d99f5bb3d1a9b09ac3/pages/blog/%5B...slug%5D.js#L5).

We'd get most Markdown formatting for free with either [MDX](https://mdxjs.com/) or [remark](https://www.npmjs.com/package/remark), but I think we'd need to bring in something like [Prism](https://github.com/FormidableLabs/prism-react-renderer) to do code highlighting.

## Nextra

[Nextra](https://nextra.vercel.app/) is a plugin for Next.js which supports generating documentation from Markdown files. It will generate a sidebar, render Markdown, and has support for code highlighting. It can be integrated into the current Next.js app without too much trouble.

However, it does not appear to be very actively developed at this time, and its authors state that it is not production ready.

## Docusaurus

Alternatively, we can deploy a separate application which will take care of generating documentation pages from Markdown. [Docusaurus](https://docusaurus.io/) is an excellent option. It will render Markdown with MDX, highlight code, generate sidebars and page listings, and can be integrated with Algolia if you wish to make the site searchable.

Quintel uses Docusaurus for [its documentation website](https://docs.energytransitionmodel.com/main/intro/).

The downside is that it's a separate application, which may limit the ability to more tightly integrate it with the rest of the HOLON application. It may provide a good stop-gap solution until the requirements for the WIki are clearer.

## MkDocs, perhaps with [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/customization/)

Similar to Docusaurus except written in Python. Supposedly simpler, but slightly less flexible when it comes to theming.

## Conclusion

All three options would require experts to edit Markdown documents and to be comfortable committing their changes using Git.

A separate website with Docusaurus (or something similar) would ensure that documentation is kept separate from the main application code, limiting the harm a non-developer could do to the main app.

On the other hand, creating documentation pages with Next.js would be reasonably easy and simpler to deploy.

### Unanswered questions

- Do experts really need to edit pages through the browser?
- Are experts technically competent enough to edit Markdown files and commit changes?
- Is it a *requirement* for the sidebar to be dynamically generated based on the file structure?
- How many documentation pages do we expect there to be, and how often will they change?
- Should anyone be able to edit documentation pages, or just authorised users?
- Do we need to do anything with the documentation content, other than show the whole page (for example, showing excerpts in tooltips on other pages)?

While I think Next.js pages and Docusuarus are both good options, we need to consider these questions to be sure that we understand what Auke and others really want out of a Wiki.

**Comment by mattijsstam** [comment]
Solution for first setup -> Nextjs static pages rendered from markdown files with MDX

**Comment by mattijsstam** [comment]
@pascalalferink see more information here https://nextjs.org/docs/advanced-features/using-mdx
