### ISSUE TITLE
Tick marks voor discrete sliders om duidelijk te maken dat het gaat om discrete stappen

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#774]
Het kan verwarrend zijn voor gebruikers waarom de slider terugspringt naar de discrete stappen. Voorbeeld:
![image](https://github.com/ZEnMo/Holon-webapp/assets/78690362/4e086f44-d733-4e02-af6a-9b3f1be1458a)

Of zoals in gas.holontool.nl (tool van Anthony)
![image](https://github.com/ZEnMo/Holon-webapp/assets/78690362/f4d26c85-c61e-4bae-8c4a-86d3aa6624b2)

**Comment by pascalalferink** [comment]
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/5c3ff982-0218-4665-a5d2-be9a6daafe6c)
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/91e9b854-aed5-4277-8d46-60362d154854)

Ook zijn in Firefox de sliders afgerond

**Comment by thesethtruth** [comment]
Super snel gedaan!

**Comment by pascalalferink** [comment]
@kasperbosman  om input gevraagd:

> daarvoor zou ik material design aanhouden, en in ons geval een donkere lijn (huidige lijn) met daar op witte stippen die de stappen vertegenwoordigen

https://m2.material.io/components/sliders#discrete-sliders

**Comment by pascalalferink** [comment]
Het eindresultaat:

![Image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/28899c7c-43a4-4186-af59-736386074658)

**Comment by thesethtruth** [comment]
Maar als ik het goed begrijp zegt @kasperbosman om puntjes/stippen te gebruiken in lijn met material design
![image](https://github.com/ZEnMo/Holon-webapp/assets/78690362/a53275ca-30fb-4581-a968-a3d95e495b8a)

En heb jij nu witte strepen langer dan de slider rail gemaakt?

**Comment by pascalalferink** [comment]
Overleg gehad met @thesethtruth : @kasperbosman 's mening is leidend. De ticks blijven vierkant

**Comment by pascalalferink** [comment]
In theorie is het mogelijk om 50 ticks te hebben. Dit ziet er niet uit (hele balk wit). Daarom worden deze ticks alleen getoond wanneer er maximaal 11 zijn. Indien er meer dan 11 stappen zijn, worden de ticks niet weergeven.

Ik heb ook onderzocht of bijvoorbeeld de helft van de ticks getoond kan worden, maar omdat de range geheel vrij is, zal het voorkomen dat een tick niet bij een echte stap komt te staan.
