### ISSUE TITLE
Toevoegen meer I'tjes

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#777]
### I'tje met uitleg met bij opschaling KPIs
- [ ] Verschillende uitleg per niveau (lokaal, regionaal en nationaal)
- [ ] Te configureren per pagina (casus/verhaallijn) welke wiki pagina de uitleg geeft
- [ ] popover zoals bij de KPI's maar dan zonder de link naar de wiki

### i’tje met met uitleg bij kosten baten
![image](https://github.com/ZEnMo/Holon-webapp/assets/78690362/53a00f09-7c9f-4910-84de-4e936f8e2f02)
- [ ] Geen knop maar een ( I )
- [ ] Te configureren per scenario 
    - [ ] Verwijzing naar een wiki pagina (link veld) (nieuw tab openen)

### i’tje met met uitleg bij genestheid naast de huidige legenda
![image](https://github.com/ZEnMo/Holon-webapp/assets/78690362/dd232bbb-5aa8-4496-a606-0cf87e7a05ba)
- [ ] Gewoon knoppen en teksten, al die icoontjes dat is uhh
- [ ] Te configureren per pagina (casus/verhaallijn)
    - [ ] Popover zoals met de "terms" links

**Comment by thesethtruth** [comment]
@kasperbosman @pascalalferink wat is de status van dit issue?

**Comment by pascalalferink** [comment]
- Opschaling KPI's, omdat het radio-buttons zijn, maakt het verwarrend om er ook omcirkelde i'tjes toe te voegen. Samen met @kasperbosman adviseren we om de uitleg hiervan in de tekst in de linkerkolom te plaatsen.

Bij kosten baten wordt een popover toegevoegd (rechts van de titel) (net zoals bij de kpi's )

Holarchy: i'jtes bij Legenda worden verwijderd, naast de legenda komt een I
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/76013369-7b80-436e-9374-985ca14951ff)
