### ISSUE TITLE
Sandbox bug: geen decimalen bij slider

### ISSUE THREAD

**Issue by Erikvv** [ZEnMo/Holon-webapp#784]
Binnenkomst via Gillis.

1. Bv slider netcapaciteit agrohub gaat in uitdaging met increments van .5 maar in sandbox increments alleen visueel maar niet numeriek.
2. Bv in casus agrohub: slider "aantal melkveebedrijven" gaat in uitdaging van 0 naar 64 maar in sandbox van 0 naar 100.

**Comment by Erikvv** [comment]
Ik heb gevraagd aan @broekhuisg en @pascalalferink of ze misschien snel weten waar het aan ligt, anders kan ik het verder onderzoeken.

**Comment by pascalalferink** [comment]
Oorzaak: bij Sandbox worden discretizationSteps genegeerd (zie #721)
Voorgestelde oplossing: bij sandbox wordt discretizationSteps wél gerespecteerd wanneer deze groter is dan de range van de slider (maximale waarde - minimale waarde) (en het dus stapjes zijn die kleiner dan één zijn)

Sandbox Voorbeeld 1: omdat het aantal stappen groter is dan het verschil tussen min en max worden hier kleinere stapjes getoond
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/c77015be-9c56-45a0-8dfb-efc06fe83d5c)
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/683bead9-d52a-4daf-b10c-d8a9004bd765)

Sandbox Voorbeeld 2: omdat het aantal stappen kleiner is dan het verschil tussen min en max wordt hier de Discretization steps genegeerd.
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/5b50367c-a156-4458-a4c0-bf5592a44035)
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/be2b2803-9807-4e93-81f6-eb89014c0214)

**Comment by Erikvv** [comment]
Ik zou zeggen houdt ook rekening met wat gemakkelijk implementeerbaar is zo laat in het project. Deze issue is minder belangrijk dan https://github.com/ZEnMo/Holon-webapp/issues/783

**Comment by thesethtruth** [comment]
Besproken met @Erikvv en we zijn akkoord met je voorstel om een extra veld toe te voegen in het CMS. Welke gebruikt wordt als die wel is ingevuld en anders terugvalt op stepSize = 1.

**Comment by pascalalferink** [comment]
Extra veld is toegevoegd:
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/6b79ef3c-d378-4ded-831d-31b71c0ab3a5)

Sandbox pagina: (stapjes van 0.5)
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/3dfac619-88ad-4c55-9be7-9ddcd12302e8)

Storyline pagina: (stapjes van 2.5)
![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/192ecda7-e792-43ec-ad2d-7553e3aff5b2)
