### ISSUE TITLE
Scenario save does not work on acceptance

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#786]
**Describe the bug**
No URL is generated but the param `undefined` is returned.

**To Reproduce**
Make a scenario, try to get the link.

**Screenshots**
![image](https://github.com/ZEnMo/Holon-webapp/assets/78690362/f2743229-f7aa-43f2-b37c-42e3a01be805)

**Comment by MariaBee3** [comment]
@Erikvv Did you add the api key of tinyUrl to the Azure environment? That is probably the cause. However, I would also like to make sure that if no tiny url is returned that the long url is then rendered. I will adjust this in the code.

**Comment by MariaBee3** [comment]
@Erikvv Ja ik had deze gemaild, was deze niet goed aangekomen? Zo heb ik het in de local .env gezet: NEXT_PUBLIC_TINY_URL_API_KEY="QyZy5hS6S9jLc4GMNOgAbcZrOGgMWoEgRNSvawEpos99hrymRJrjpccKvYQB"
Ik denk dat dit overal hetzelfde kan zijn, al heb ik daar niet veel ervaring mee.

**Comment by Erikvv** [comment]
Ik heb deze ingesteld maar bij de request naar tinyUrl is de header "authorization: Bearer undefined". Als het in dev wel werkt zal ik er nog dieper naar moeten kijken.

**Comment by MariaBee3** [comment]
@Erikvv Vervelend dat het niet gelijk werkt.  Wellicht dat Mattijs anders nog ideeën heeft. Laat je weten als het werkt?

**Comment by thesethtruth** [comment]
@Erikvv even een bump. Fijn als we dit toch nog z.s.m. rond kunnen krijgen zodat we het voor volgende week dinsdag gevalideerd hebben dat het werkt. Dinsdag is namelijk interne oplevering.

**Comment by Erikvv** [comment]
Ik heb het lokaal getest en het probleem is er nog steeds. Dit is dus geen configuratie issue.

Het probleem lijkt me dat de API_KEY gelezen wordt uit `process.env`, maar dit bestaat niet in de browser-omgeving.

Waarom het bij Maria wel werkt weet ik niet. Test het eventueel met de productie container ipv de dev container.

**Comment by MariaBee3** [comment]
@Erikvv Ik heb de code aangepast: de apicall wordt nu vanuit API routes uitgevoerd. Hiermee zou het wel moeten werken. Kan jij reviewen?
