### ISSUE TITLE
In sandbox the kostenbaten view does not take up the whole space underneath the header

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#792]
**Describe the bug**

**To Reproduce**
1. Go to https://holon-v2-acceptatie.azurewebsites.net/casus-overzicht/bedrijventerrein-energy-hub/bedrijventerrein-sandbox/
2. Click on kosten baten button

**Expected behavior**
The kostenbaten view should take up the whole available space in the sandbox mode just like in the other modes

**Screenshots**
![image](https://github.com/ZEnMo/Holon-webapp/assets/78690362/76190029-8ab1-4f29-9012-650e34d6a093)

**Comment by MariaBee3** [comment]
This had to do with the new height of the header (it became smaller when we removed the login button). I've adjusted the section menu bar, the holarchy tab and the kostenbaten view.
