### ISSUE TITLE
'Reken door' modal is niet zichtbaar bij veel tekst of interactieve elementen per sectie

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#804]
### Stappen om te tonen
1. Ga naar https://holon-v2-acceptatie.azurewebsites.net/casus-overzicht/transitievisie-warmte-gemeente/sandbox-transitievisie-warmte/
2. Wacht op initiele resultaat
3. Trek aan een slider
4. Zie dat het rechter deel (afbeelding + dashboard) wel grijs wordt maar dat de reken door modal niet in beeld is

### Gewenst gedrag
De modal lijnt uit met het rechter deel (afbeelding + dashboard) zodat de modal altijd in beeld is, ook bij langere secties

**Comment by pascalalferink** [comment]
Uitlijning van modal is aangepast, modal staat niet meer verticaal gecentreerd, maar lijnt uit met de bovenkant. Wanneer de gebruiker naar beneden scrolt, wordt de modal sticky

![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/ca80bd40-faf9-4bbe-ad72-8f311b1f84f9)

**Comment by thesethtruth** [comment]
Slim dat je aan de sticky hebt gedacht! Daar had ik niet over nagedacht. Super Pascal!
