### ISSUE TITLE
'www' subdomain of holontool.nl does not point to the webapp at Azure

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#82]
1. Navigate to [www.holontool.nl](www.holontool.nl)
2. See the following:
![image](https://user-images.githubusercontent.com/78690362/183614559-5c0e5b3a-3e9c-4eb4-a9ca-43a8093bf920.png)
3. confuus

**Comment by mattijsstam** [comment]
@thesethtruth dit kun je vrij eenvoudig oplossen door in azure een nieuw custom domain www.holontool.nl te koppelen en de DNS weer aan te passen. Aangezien jij rechten hebt voor beidde systemen heb ik jou aan de issue gekoppeld.

Ik zie dat www.holontool.nl momenteel nog naar 149.210.170.156 verwijst wat een transip ip is.

**Comment by Erikvv** [comment]
Was al opgelost.
