### ISSUE TITLE
Wiki menu dikgedrukte items

### ISSUE THREAD

**Issue by Erikvv** [ZEnMo/Holon-webapp#823]
Door @PeterHogeveen 

Hij drukt paginas zonder child page niet dik en paginas met child page wel.

red: gewenste functionaliteit moet gespecced worden

![download](https://github.com/ZEnMo/Holon-webapp/assets/1748197/54b854c1-e795-4346-ae04-2555cbfc3eb5)

**Comment by thesethtruth** [comment]
Dit is gewenst gedrag. Hiermee maak je het aan de gebruiker duidelijk welke wiki pagina's nog verder uit kunnen klappen en welke niet.
