### ISSUE TITLE
Frame from i'tje is projected below front end items causing unclear visuals (see picture)

### ISSUE THREAD

**Issue by naudloomans** [Zenmo/Holon-webapp#847]
**Describe the bug**
Frame from i'tje is not project over other front end items such as the slider input value (see picture)

**To Reproduce**
1. Go to a slider interactive element with i
2. See if it falls over a slider when clicking on the i

**Expected behavior**
The window depicted when clicking on the i should be on top of all other items

**Actual behavior**
The window depicted when clicking on the i is below some items

**Screenshots**
![afbeelding](https://github.com/ZEnMo/Holon-webapp/assets/38351577/fcdfb831-a714-47e1-9d62-0d0e963bcbc3)

**Additional context**

**Add labels**
- [ ] Correct label for origin (e.g. `bug` of `feature enhancement` of `nice to have`)
- [ ] Correcte label voor categorie (e.g. `interactive element configuratie`)

**Comment by Erikvv** [comment]
Fixed @jaccokw
