### ISSUE TITLE
TVW Buurtholonen kapot

### ISSUE THREAD

**Issue by Erikvv** [ZEnMo/Holon-webapp#853]
Melding van Jorrit en staat ook in de feedback van 10 juli

> Wel/geen buurtholon vormen leidt niet tot verandering van de KPIs  

Vreemd verschijnsel:

Op productie is in casus TVW het interactief element "Buurtholonen actief" spontaan kapot gegaan. Als je dit aanzet is er een fout in AnyLogic. 

```
something went wrong: status: FAILED, message: {"type":"INTERNAL","message":"NullPointerException: null","details":["java.lang.NullPointerException","\\tat base.ConnectionOwner.lambda$0(ConnectionOwner.java:670)","\\tat com.anylogic.engine.UtilitiesCollection.findFirst(Unknown Source)","\\tat base.ConnectionOwner.f_connectToParentActor(ConnectionOwner.java:670)","\\tat base.Main.f_createActors(Main.java:5944)","\\tat base.Main.f_configureBackBone(Main.java:4986)","\\tat base.Main.onStartup(Main.java:7414)","\\tat com.anylogic.engine.Agent.d(Unknown Source)","\\tat com.anylogic.engine.Agent.start(Unknown Source)","\\tat com.anylogic.engine.Engine.start(Unknown Source)","\\tat com.anylogic.cloud.executor.connector.ExperimentSimple.run(ExperimentSimple.java:105)","\\tat com.anylogic.cloud.executor.connector.ExperimentSimple.startRun(ExperimentSimple.java:221)"]}
```

We hadden afgesproken niet te werken in het CMS op productie. Als iedereen zich daar aan heeft gehouden zit er mogelijk iets in de rule engine wat het element in de database kapot maakt. 

Jorrit geeft aan dat dit al 4 keer eerder op acceptatie is gebeurd, en dat hij het toen opgelost heeft door het element te verwijderen en opnieuw in te stellen. 

FYI @JorritvandenHouten vul s.v.p. aan als je nog meer info hebt.

**Comment by JorritvandenHouten** [comment]
Wat aanvullende info: 
-foutmelding AnyLogic treedt op omdat holon-contracten (child-objects) niet meer goed worden toegevoegd aan sommige (maar niet alle!) buurten.
-op acceptatie werkt precies datzelfde interactieve element nog wel. Problemen ontstonden voorheen soms na bijvoorbeeld openen en opnieuw opslaan van het interactief element (bijvoorbeeld na toevoegen juridische content door Naud). Nu ook a.g.v. migratie naar productie.
-Link naar het interactief element: https://holon-v2-[acceptatie.azurewebsites.net/wt/cms/snippets/holon/interactiveelement/edit/444187/](link)
-In de sandbox staan soortgelijke interactieve elementen, maar dan per buurt. Een of meerdere/alle van deze elementen lijken op productie ook stuk te zijn gegaan, want hier treedt dezelfde fout op. Bijv: [https://holon-v2-acceptatie.azurewebsites.net/wt/cms/snippets/holon/interactiveelement/edit/444084/](link).

**Comment by Erikvv** [comment]
Er zit een jQuery error op de CMS pagina betreffende 2e order relatie filter. Dit kan mogelijk van invloed zijn.

**Comment by Erikvv** [comment]
De rekenregels werden in een andere volgorde werden uitgevoerd dan dat ze in het CMS zichtbaar zijn.

Ik heb het aangepast dat ze nu worden uitgevoerd op volgorde van regel id.

Waarschijnlijk was dit non-deterministisch en dit verklaart waarom het spontaan kapot leek te gaan of kapot ging na het overzetten naar prod. 

(Die jQuery error is er overigens nog steeds maar ik vind het belangrijker eerst de back-end te verbeteren als we hier nog aan gaan werken).
