### ISSUE TITLE
Cooky policy pagina en actie cookies weigeren

### ISSUE THREAD

**Issue by naudloomans** [Zenmo/Holon-webapp#861]
**Describe the bug**
1) A cooky policy is required linked from the cooky pop-up which links to https://holontool.nl/cookie-policy/
2) Make sure that when clicked on 'weigeren' cookies are switched off

**To Reproduce**
1. Go to holontool.nl in private tab
2. Check cooky policy

**Expected behavior**
A working cooky policy page and cookies switch off when denying cookies

**Actual behavior**
Not sure if all cookies switch of, no cookie page

**Comment by Erikvv** [comment]
Aangepast dat tracking via Microsoft Application Insights alleen aan staat als de banner geaccepteerd is. 

Google Analytics verwijderd.

**Comment by Erikvv** [comment]
Ik heb de link verwijderd en gewoon in de melding gezet dat Azure Application Insights ingeschakeld wordt bij accepteren.

Ik weet niet wat ik er verder bij moet zetten, zijn allemaal nogal open deuren.
