### ISSUE TITLE
Begin iedere sectie duidelijk maken dat settings vast ingesteld zijn

### ISSUE THREAD

**Issue by Erikvv** [ZEnMo/Holon-webapp#864]
Feedback van 10 juli

> Wordt er altijd doorgebouwd op alle voorgaande stappen of alleen in het geval van de verhaallijnen. Ik zal dit duidelijker maken.

**Comment by petertue** [comment]
We hebben bij de betreffende secties meer duidelijk aangegeven. Niet bij begin iedere sectie, dat werd een beetje veel
