### ISSUE TITLE
Enkel/meervoud klopt niet overal bij mouse-over tabel: “Commerciele bedrijven betaalt x aan y”

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#886]
We moeten even kijken of we dit snel kunnen aanpassen. Zo niet, dan blijven we erbij dat het als groep beschouwd wordt.

**Comment by Erikvv** [comment]
Ik heb het aangepast dat hij meervoud gebruikt als het onderwerp eindigt op -en of -s.

Het lijkt me nu handig de group "Huishouden" te hernoemen naar "Huishoudens".
