### ISSUE TITLE
Agro uitkomsten tussen verhaal en uitdaging verschillen

### ISSUE THREAD

**Issue by petertue** [ZEnMo/Holon-webapp#900]
Feedback RvO:
_Uitkomsten verhaallijn en challenge verschillen bij dezelfde configuratie: Wel zon op stal (beide) en geen zonnepark (beide) > netbelasting 57.4 en  45.3. Ook de andere waardes wijken af! Hoe kan dat? Het verschil lijkt te bestaan bij alle configuraties. De veschillen zijn soms meer dan 10 % !_

**Comment by GillisHommen** [comment]
Is gefixt (op acceptatie), deze casus maakt gebruik van invisible-sliders om bepaalde parameters te schalen, en die stonden niet goed ingesteld in de storyline.
