### ISSUE TITLE
jQuery error op CMS pagina.

### ISSUE THREAD

**Issue by Erikvv** [ZEnMo/Holon-webapp#902]
Bij het bewerken van een verhaallijn, uitdaging of sandbox is er de error `TypeError: interactiveElementName is undefined`.

**Comment by Erikvv** [comment]
Dit zat in een hacky stukje code wat inputs veranderde naar type=number of selectboxes.

**Comment by Erikvv** [comment]
tag @GillisHommen ik denk niet dat dit jouw probleem heeft veroorzaakt.

**Comment by GillisHommen** [comment]
Welk probleem ging dit ookweer over?

**Comment by Erikvv** [comment]
@GillisHommen Iets in de richting dat de eerste keer opslaan na het toevoegen van een interactief element niet goed ging en daarna wel.
