### ISSUE TITLE
Bedrijventerrein - vermogen zonnepark bug

### ISSUE THREAD

**Issue by Erikvv** [ZEnMo/Holon-webapp#914]
Als ik op prod "Bedrijventerrein - vermogen zonnepark" op 4 MW zet is er geen resultaat.

**Comment by GillisHommen** [comment]
Als ik de bedrijventerrein verhaallijn open en in de sectie 'eigen opwek' het zonnepark vermogen op 4MW zet, krijg ik wel resultaat:

![image](https://github.com/ZEnMo/Holon-webapp/assets/98752265/33a43aec-8650-4de0-9bf9-d2c6fa4bd57c)

Is dit ook wat jij gedaan hebt? Zo niet, kun je me helpen het probleem te reproduceren?

**Comment by Erikvv** [comment]
Kan het niet meer reproduceren.
