### ISSUE TITLE
Industriecasus verhaallijn sectie "Windmolens op zee" niet opgepakt door cache runner

### ISSUE THREAD

**Issue by Erikvv** [ZEnMo/Holon-webapp#923]
Alle verhaallijnen werken na een verse cache run behalve dit onderdeel. Onderzoeken

Web request:

```
{
    "interactive_elements":[
        {"interactive_element":444191,"value":100},
        {"interactive_element":444192,"value":15},
        {"interactive_element":444194,"value":20}
    ],
    "scenario":466791
}
```

**Comment by Erikvv** [comment]
Dit kwam doordat de startwaarde van "Totaal geinstalleerd vermogen elektrolysers" op 7 GW stond maar dit is geen waarde die valt tussen 0 en 20 met stapjes van 5.

Ik heb de startwaarde op 5 GW. Ik doe geen code aanpassingen, lijkt me niet nodig voor dit geval.

**Comment by GillisHommen** [comment]
Ja, dit is prima! Ik dacht eigenlijk ook dat ik 'm op 5GW default had gezet, maar misschien was dat alleen in de challenge, niet in de verhaallijn.
