### ISSUE TITLE
Content managers can use the CMS to create storylines

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#93]
**Description**

To be able to configure storylines in the CMS several interactive components have to be build to create the [design](https://xd.adobe.com/view/80716de6-fae6-4d41-82fb-e5a5d67de795-d522/screen/6ff34b16-350d-4985-be49-6b394e54e633)

![Image](https://user-images.githubusercontent.com/32770108/193806860-0dc73e64-0dcb-4332-ae3f-0ccb46d3f6fb.png)

A storyline should be a single CMS page where users can add sections, the section can have the following elements:

- Static block (text image, text video, etc)
- Dynamic block, which has the following configurable items:
  * Text 
  * Sliders (default values) (exposed or not)
  * Radio buttons (default state) (exposed or not)
  * Scenario (which scenario is used in this section)
  * Kpi's (which kpi's are shown)

Therefore a list should be available in the CMS with the following items:

- Scenario's (list from database with scenario names)
- All available sliders (range, text, model link)
- All available radio buttons (options, texts, model link)

For the model configuration we use the model interface data format #91 

**To discuss**

- Do the proposed configurable items include every possible scenario or are there settings missing?
- Can the animation be controlled by showing or hiding layers or is it more difficult?
- Which sliders and radio buttons are available?
- Which metadata should a storyline have?
  * Type rol
  * Type informatie
  * Title
  * Short description
  * Image

**Acceptance criteria**

- [ ] Content managers can add a storyline page
- [ ] Content managers can add static content to a storyline page
- [ ] Content managers can add dynamic content to a storyline page
- [ ] Only a single static block can be added to a storyline?
- [ ] A storyline should have at least 1 dynamic block

**Comment by mattijsstam** [comment]
![Image](https://user-images.githubusercontent.com/32770108/194321713-d6d6b28e-5876-4352-b8d7-1474cd62b4bf.png)
