### ISSUE TITLE
Experts can add new wikipedia articles to the wiki by using a WYSIWYG text editor

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#94]
**Description**

This issue has the goal to make the current wiki pages configurable with the newly added Wagtail CMS.
Wagtail provides an alternative to the default WYSIWYG editor with blocks as described in https://docs.wagtail.org/en/stable/topics/streamfield.html. 

**To discuss**

- Which blocks should be created in Wagtail?
- Which data is configured in the CMS to render the wiki pages?
- How is nextjs going to construct the wiki out of the pages api provided from Wagtail?

**Acceptance criteria**

- Admins can create static pages in Wagtail to create a "wiki"
- Admins can use predefined blocks to create visual attractive pages
- Users can browse trough the page hierarchy in the frontend

**Comment by mattijsstam** [comment]
Dependent on #92
