### ISSUE TITLE
Scenario opslaan / delen knop

### ISSUE THREAD

**Issue by patrickkerling** [Zenmo/Holon-webapp#964]
TYPE
UX/Technisch

LOCATIE/URL
Verhaalmodus, uitdaging en sandbox

PROBLEEM
Het icoon van de knop "scenario delen" komt niet overeen met de actie die erbij hoort + de opties die gebruikers hebben in de pop-up.

BESCHRIJVING
Het icoon veranderen van een opslaan icoon naar een deel icoon.

ACTIES
UX design maken icm briefing

TE VINDEN IN PPT ONDER #3

**Comment by patrickkerling** [comment]
Suggestie:

- verplaatsen van de locatie, de knop naar holarchie past inhoudelijk beter bij de knop kosten en baten en de KPIS
- zelfde opmaak als de kosten-baten knop (heeft ook eenzelfde werking)
- scenario delen dan bovenaan plaatsen en iets anders opmaken

![Uploading 202406 - Holon fase 2 - Verhaalmodus 1.png…]()

**Comment by Erikvv** [comment]
@patrickkerling het uploaden van het plaatje is mislukt, iets meer geduld. Misschien is het handig het hele Figma document te delen?
