### ISSUE TITLE
Knop naar holarchie (verhaalmodus en uitdagingen) voorzien van een label

### ISSUE THREAD

**Issue by patrickkerling** [Zenmo/Holon-webapp#970]
TYPE
UX/Technisch

LOCATIE/URL
Verhaalmodus, uitdaging, sandbox

PROBLEEM
Het icoon op zichzelf geeft onvoldoende aan wat de gebruiker kan verwachten achter deze knop. 

BESCHRIJVING
Een klein label toevoegen "holarchie" zou al beter zijn. Vraag, is deze term voor de gemiddelde gebruiker voldoende duidelijk? Wellicht iets om met het content bureau te bespreken.

TE VINDEN IN PPT #10

**Comment by Erikvv** [comment]
Done
