### ISSUE TITLE
Hoofdnavigatie hoeft niet altijd in beeld te zijn

### ISSUE THREAD

**Issue by patrickkerling** [Zenmo/Holon-webapp#971]
TYPE
UX/Technisch

LOCATIE/URL
Gehele website

PROBLEEM
De navigatie altijd in beeld hebben kan waardevol zijn, vooral bij websites met een complexe structuur en/of veel content. Dat is hier niet het geval en daar komt bij dat we de gebruiker vooral in de rekentool willen laten werken. We verwachten dat de gebruiker niet heel veel door de website heen klikt en voor zover dat wel gebeurt is daar een navigatie die altijd in beeld is (ook bij scrollen) niet nodig.

BESCHRIJVING
Navigatie enkel in beeld laten (bovenaan het venster) wanneer de gebruiker naar boven scrollt, maar zodra deze naar beneden scrollt verdwijnt deze weer. Dit geeft ons meer verticale ruimte om mee te werken en gebruiker datgene te laten zien waar het echt om draait.

TE VINDEN IN PPT #11

**Comment by Erikvv** [comment]
Gedaan
