### ISSUE TITLE
Legenda (knop) toegankelijker maken

### ISSUE THREAD

**Issue by patrickkerling** [Zenmo/Holon-webapp#980]
TYPE
UX/Technisch

LOCATIE/URL
Holarchie 

PROBLEEM
De knop die de legenda weergeeft valt totaal weg in de interface, deze zien gebruikers gegarandeerd over het hoofd.

BESCHRIJVING
Opmaak en locatie aanpassen.

**Comment by jaccokw** [comment]
Het idee is nu om de legenda permanent in het linkergedeelte op te nemen. Knop komt dan te vervallen. @patrickkerling wat vind jij daar van?

**Comment by patrickkerling** [comment]
Dit kan zeker een optie zijn. Zeker icm de visuele wijziging voor de sliders (https://github.com/Zenmo/Holon-webapp/issues/982#issuecomment-2139377248), 

ik zou dit wel in een wireframe uit willen werken, zodat we goed het effect hiervan kunnen zien en ook de relatie met de rest van de interface. Met als doel om het duidelijker te maken.

**Comment by Erikvv** [comment]
![holarchie-voor](https://github.com/Zenmo/Holon-webapp/assets/1748197/ca0888b9-92a0-46c3-ad00-d1c7226acfbb)

![holarchie-na](https://github.com/Zenmo/Holon-webapp/assets/1748197/39882537-7c48-4813-a424-0a7e00a0a857)

**Comment by patrickkerling** [comment]
Ziet er goed uit. Stap in de goede richting. 
Wat me nu opvalt (maar dat zou niet bij dit issue horen) is dat we vrij veel tekst bold hebben op dit moment (kopjes, maar ook de antwoorden/keuzeopties). Maakt het wat druk en zorgt ervoor dat de gebruiker niet direct een overzicht heeft (visueel). Ik maak er even een apart issue voor aan, moeten we maar even kijken of we daar ook wat mee willen.
