### ISSUE TITLE
Holarchie op eenzelfde manier presenteren als kosten-baten (als pop-up)

### ISSUE THREAD

**Issue by patrickkerling** [Zenmo/Holon-webapp#981]
TYPE
UX/Technisch

LOCATIE/URL
Holarchie 

PROBLEEM
Holarchie ook een kruisje rechtsboven geven, zodat de gebruiker deze kan sluiten en op eenzelfde manier opmaken als de kosten-baten.

BESCHRIJVING
Zie hierboven.

TE VINDEN IN PPT: 26

**Comment by Erikvv** [comment]
Done
