### ISSUE TITLE
H1 style ontbreekt in "Text and Media"-element

### ISSUE THREAD

**Issue by jaccokw** [Zenmo/Holon-webapp#989]
In een pagina van het type _Static_ is in de _Page body_ een _Text and Media_-element aangemaakt. Het lukt daarin niet om de style H1 toe te passen.

![image](https://github.com/Zenmo/Holon-webapp/assets/169782263/64a860ae-f679-4238-a718-867628d58d1d)

**Comment by Erikvv** [comment]
Deploy naar acceptatie loopt. @jaccokw
