### ISSUE TITLE
Bold tekst en kopjes optimalisatie

### ISSUE THREAD

**Issue by patrickkerling** [Zenmo/Holon-webapp#999]
Probleembeschrijving: op dit moment is veel tekst in de rekentool "vet". Dit zorgt voor een wat druk geheel en mist daardoor wat overzicht.

Locatie: gehele rekentool, incl holarchie.

Suggestie: antwoordopties niet meer bold maken?

**Comment by patrickkerling** [comment]
He Erik,

ik had deze snel even aangemaakt om in ieder geval de bevinding even vast te leggen, hoeft op zich niet direct wat mee te gebeuren. Maar wat is de reden om deze nu te sluiten?

**Comment by Erikvv** [comment]
Ik heb de radiobutton opties niet meer bold gemaakt. 

Op andere plekken wordt idd nog onnodig/overmatig gebruik gemaakt van bold tekst, ik zal het open laten om daar later nog eens naar te kijken.

**Comment by patrickkerling** [comment]
aah check, thanks! Ik vroeg t me vooral af. Dank je!
